"""Curated pipeline payloads for 5 demo projects (dashboard + project UI testing).

Each fixture mirrors a real-world construction project with authentic details:
permits, schedules, suppliers, crew allocations, and building definitions
generated by the template engine.
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from typing import Any

from app.services.building_templates import generate_building_definition

PIPELINE_AGENTS: tuple[tuple[str, str, str], ...] = (
    ("ContractAgent", "4", "projectSummary"),
    ("BlueprintAgent", "5", "blueprintSummary"),
    ("PermitAgent", "3", "permitAssessment"),
    ("ScheduleAgent", "2", "projectPlan"),
    ("SupplierAgent", "3", "supplierAnalysis"),
    ("CrewAgent", "2", "crewAnalysis"),
)


def _attach_building_definition(pipeline: dict[str, Any]) -> dict[str, Any]:
    blueprint = pipeline.get("blueprintSummary")
    project = pipeline.get("projectSummary")
    if isinstance(blueprint, dict):
        blueprint["building_definition"] = generate_building_definition(
            blueprint,
            project if isinstance(project, dict) else {},
        )
    return pipeline


def build_execution_records(
    pipeline: dict[str, Any],
    *,
    base_time: datetime | None = None,
) -> list[dict[str, Any]]:
    """Build 6 agent execution records with sequential timestamps."""
    started = base_time or datetime.now(timezone.utc)
    records: list[dict[str, Any]] = []
    offset_minutes = 0
    for agent_name, version, payload_key in PIPELINE_AGENTS:
        step_start = started + timedelta(minutes=offset_minutes)
        step_end = step_start + timedelta(minutes=2)
        offset_minutes += 3
        output = pipeline.get(payload_key) or {}
        records.append(
            {
                "agent_name": agent_name,
                "agent_version": version,
                "status": "complete",
                "started_at": step_start,
                "completed_at": step_end,
                "output": output,
            }
        )
    return records


# ---------------------------------------------------------------------------
# Project 1: Hudson Yards-style Supertall Office Tower — Manhattan, NYC
# ---------------------------------------------------------------------------


def _hudson_tower_fixture() -> dict[str, Any]:
    return _attach_building_definition({
        "projectSummary": {
            "project_name": "550 West 34th Street — Hudson Yards Tower C",
            "client_name": "Related Companies & Oxford Properties Group",
            "location": "550 West 34th Street, New York, NY 10001",
            "project_type": "Class A Commercial Office Tower",
            "budget": 3240000000,
            "duration_months": 48,
            "scope": (
                "73-story supertall office tower (1,296 ft) with 2.9M GSF of Class A "
                "office space, ground-floor retail, observation deck on floors 70-73, "
                "triple-height lobby, 6 levels of below-grade parking. Structural system: "
                "composite steel/concrete core with outrigger trusses at mechanical floors. "
                "Full curtain wall facade with triple-glazed high-performance IGUs."
            ),
            "square_footage": 2900000,
            "floor_count": 73,
            "complexity_level": "Critical",
            "start_date": "2025-09-15",
            "target_completion_date": "2029-09-15",
            "milestones": [
                {"name": "Notice to Proceed", "date": "2025-09-15"},
                {"name": "Excavation Complete", "date": "2026-04-30"},
                {"name": "Mat Foundation Pour", "date": "2026-07-15"},
                {"name": "Steel Topping Out", "date": "2028-03-01"},
                {"name": "Curtain Wall Completion", "date": "2028-09-30"},
                {"name": "Core & Shell Substantial Completion", "date": "2029-03-15"},
                {"name": "TCO — Floors 1-35", "date": "2029-06-01"},
                {"name": "Final Certificate of Occupancy", "date": "2029-09-15"},
            ],
        },
        "blueprintSummary": {
            "construction_type": "Type I-A (Non-combustible, fully sprinklered)",
            "stories_above_grade": 73,
            "stories_below_grade": 6,
            "structural_steel_tons": 46200,
            "concrete_cy": 185000,
            "curtain_wall_sf": 620000,
            "lateral_system": "Composite concrete core + steel outrigger trusses at L25, L50, L68",
            "foundation_type": "10 ft thick reinforced mat foundation on Manhattan schist bedrock",
            "mep_highlights": {
                "electrical_service_amps": 48000,
                "elevators": 52,
                "emergency_generators_kw": 12000,
                "cooling_tons": 9200,
                "fire_pump_gpm": 3000,
            },
        },
        "permitAssessment": {
            "required_permits": [
                {
                    "name": "NYC DOB New Building Permit (NB)",
                    "category": "Municipal — NYC Dept of Buildings",
                    "status": "Approved",
                    "estimated_days": 0,
                    "permit_number": "NB-2025-034891",
                },
                {
                    "name": "Foundation & Earthwork Permit",
                    "category": "Municipal — NYC DOB",
                    "status": "Approved",
                    "estimated_days": 0,
                    "permit_number": "FW-2025-019274",
                },
                {
                    "name": "Crane Operating Permit (Tower Crane #1–#3)",
                    "category": "Municipal — NYC DOB Cranes & Derricks",
                    "status": "Approved",
                    "estimated_days": 0,
                },
                {
                    "name": "MTA Track Protection Plan Approval",
                    "category": "Transit Authority",
                    "status": "Approved",
                    "estimated_days": 0,
                },
                {
                    "name": "FDNY Fire Suppression Plan Review",
                    "category": "Life Safety — FDNY",
                    "status": "In Review",
                    "estimated_days": 18,
                },
                {
                    "name": "FAA Determination of No Hazard (Form 7460-1)",
                    "category": "Federal — FAA",
                    "status": "Approved",
                    "estimated_days": 0,
                },
                {
                    "name": "DEP Sewer Connection Approval",
                    "category": "Municipal — NYC DEP",
                    "status": "Pending",
                    "estimated_days": 30,
                },
                {
                    "name": "DOT Street Closure / Sidewalk Shed Permit",
                    "category": "Municipal — NYC DOT",
                    "status": "Approved",
                    "estimated_days": 0,
                },
            ]
        },
        "projectPlan": {
            "estimated_duration_days": 1461,
            "project_phases": [
                {
                    "name": "Mobilization & Demolition",
                    "status": "completed",
                    "start_date": "2025-09-15",
                    "end_date": "2025-12-31",
                    "progress": 100,
                },
                {
                    "name": "Excavation & Secant Pile Wall",
                    "status": "completed",
                    "start_date": "2025-11-01",
                    "end_date": "2026-04-30",
                    "progress": 100,
                },
                {
                    "name": "Mat Foundation & Below-Grade Structure",
                    "status": "in-progress",
                    "start_date": "2026-04-01",
                    "end_date": "2026-11-30",
                    "progress": 65,
                },
                {
                    "name": "Structural Steel Erection (Core & Perimeter)",
                    "status": "in-progress",
                    "start_date": "2026-09-01",
                    "end_date": "2028-03-01",
                    "progress": 18,
                },
                {
                    "name": "Curtain Wall Installation",
                    "status": "pending",
                    "start_date": "2027-03-01",
                    "end_date": "2028-09-30",
                    "progress": 0,
                },
                {
                    "name": "MEP Rough-In & Vertical Risers",
                    "status": "pending",
                    "start_date": "2027-06-01",
                    "end_date": "2029-01-31",
                    "progress": 0,
                },
                {
                    "name": "Interior Fit-Out & Finishes",
                    "status": "pending",
                    "start_date": "2028-06-01",
                    "end_date": "2029-07-31",
                    "progress": 0,
                },
                {
                    "name": "Elevator Installation & Testing",
                    "status": "pending",
                    "start_date": "2027-09-01",
                    "end_date": "2029-06-30",
                    "progress": 0,
                },
                {
                    "name": "Commissioning & Punch List",
                    "status": "pending",
                    "start_date": "2029-04-01",
                    "end_date": "2029-09-15",
                    "progress": 0,
                },
            ],
            "materials": [
                {"material_name": "Structural Steel (W-shapes, HSS, plates)", "quantity": 46200, "unit": "TON"},
                {"material_name": "Ready-Mix Concrete (8000 psi core walls)", "quantity": 125000, "unit": "CY"},
                {"material_name": "Ready-Mix Concrete (5000 psi floor slabs)", "quantity": 60000, "unit": "CY"},
                {"material_name": "Curtain Wall Unitized Panels", "quantity": 8400, "unit": "EA"},
                {"material_name": "Reinforcing Steel (Gr. 60 #11 bars)", "quantity": 18500, "unit": "TON"},
                {"material_name": "Metal Deck (3\" composite)", "quantity": 2400000, "unit": "SF"},
                {"material_name": "Spray-Applied Fireproofing", "quantity": 3200000, "unit": "SF"},
                {"material_name": "Copper Bus Duct (4000A)", "quantity": 4800, "unit": "LF"},
            ],
            "inspection_stages": [
                {"name": "Secant pile integrity testing (PDA/CSL)", "phase": "Excavation", "status": "passed"},
                {"name": "Mat foundation rebar pre-pour inspection", "phase": "Foundation", "status": "passed"},
                {"name": "Outrigger truss bolt torque verification (L25)", "phase": "Steel Erection", "status": "scheduled"},
                {"name": "Curtain wall ASTM E283/E330 mock-up testing", "phase": "Curtain Wall", "status": "planned"},
                {"name": "FDNY standpipe hydrostatic test (zone 1–3)", "phase": "Life Safety", "status": "planned"},
                {"name": "Elevator load test & governor trip test", "phase": "Vertical Transport", "status": "planned"},
                {"name": "Emergency generator full-load run test (2hr)", "phase": "Commissioning", "status": "planned"},
            ],
            "dependencies": [
                {"predecessor": "Excavation & Secant Pile Wall", "successor": "Mat Foundation & Below-Grade Structure"},
                {"predecessor": "Mat Foundation & Below-Grade Structure", "successor": "Structural Steel Erection (Core & Perimeter)"},
                {"predecessor": "Structural Steel Erection (Core & Perimeter)", "successor": "Curtain Wall Installation"},
                {"predecessor": "Structural Steel Erection (Core & Perimeter)", "successor": "MEP Rough-In & Vertical Risers"},
                {"predecessor": "Curtain Wall Installation", "successor": "Interior Fit-Out & Finishes"},
                {"predecessor": "MEP Rough-In & Vertical Risers", "successor": "Commissioning & Punch List"},
            ],
        },
        "supplierAnalysis": {
            "procurement_plan": [
                {
                    "material_name": "Structural Steel — W14x730 columns (Gr. 65)",
                    "supplier_name": "Nucor-Yamato Steel Company",
                    "quantity": 2400,
                    "unit_price": 4250.00,
                    "delivery_date": "2026-08-15",
                    "total_cost": 10200000.0,
                    "lead_time_weeks": 22,
                },
                {
                    "material_name": "Unitized Curtain Wall Panels (triple-glazed IGU)",
                    "supplier_name": "Permasteelisa North America",
                    "quantity": 8400,
                    "unit_price": 1850.00,
                    "delivery_date": "2027-02-01",
                    "total_cost": 15540000.0,
                    "lead_time_weeks": 36,
                },
                {
                    "material_name": "High-Strength Concrete 8000 psi (core walls)",
                    "supplier_name": "Ferrara Bros. Building Materials",
                    "quantity": 125000,
                    "unit_price": 195.00,
                    "delivery_date": "2026-04-01",
                    "total_cost": 24375000.0,
                    "lead_time_weeks": 2,
                },
                {
                    "material_name": "Passenger Elevators (gearless MRL, 45 ft/s)",
                    "supplier_name": "ThyssenKrupp Elevator Americas",
                    "quantity": 52,
                    "unit_price": 385000.00,
                    "delivery_date": "2027-08-01",
                    "total_cost": 20020000.0,
                    "lead_time_weeks": 48,
                },
                {
                    "material_name": "Spray-Applied Fireproofing (SFRM)",
                    "supplier_name": "Isolatek International",
                    "quantity": 3200000,
                    "unit_price": 1.85,
                    "delivery_date": "2027-01-15",
                    "total_cost": 5920000.0,
                    "lead_time_weeks": 8,
                },
            ],
            "supply_chain_risks": [
                {
                    "risk": "Curtain wall panel fabrication delay — single-source factory in Italy",
                    "severity": "High",
                    "mitigation": "Negotiate dual fabrication lines; hold 4-week float in facade schedule",
                },
                {
                    "risk": "Structural steel mill rolling schedule slip (W14x730 heavy columns)",
                    "severity": "Medium",
                    "mitigation": "Place mill order 6 months early; approve alternate W14x665 if needed",
                },
                {
                    "risk": "Elevator cab delivery constrained by global chip shortage (controllers)",
                    "severity": "Medium",
                    "mitigation": "Pre-order controller boards; accept incremental delivery in 3 batches",
                },
            ],
        },
        "crewAnalysis": {
            "crew_allocations": [
                {
                    "phase_name": "Structural Steel Erection",
                    "crew_name": "W&H Steel Erectors — Gang A (Derek Sullivan, Foreman)",
                    "skill_type": "Ironworker Local 40",
                    "headcount": 32,
                    "labor_cost": 4800000.0,
                    "start_date": "2026-09-01",
                    "end_date": "2028-03-01",
                },
                {
                    "phase_name": "Structural Steel Erection",
                    "crew_name": "W&H Steel Erectors — Gang B (Tony Marchetti, Foreman)",
                    "skill_type": "Ironworker Local 40",
                    "headcount": 28,
                    "labor_cost": 4200000.0,
                    "start_date": "2027-01-15",
                    "end_date": "2028-03-01",
                },
                {
                    "phase_name": "Curtain Wall Installation",
                    "crew_name": "Perini Facade Crew (Luis Ortega, Superintendent)",
                    "skill_type": "Glazier Local 1087",
                    "headcount": 24,
                    "labor_cost": 3600000.0,
                    "start_date": "2027-03-01",
                    "end_date": "2028-09-30",
                },
                {
                    "phase_name": "MEP Rough-In & Vertical Risers",
                    "crew_name": "Five Star Electric — High Voltage (Sofia Mendez, PM)",
                    "skill_type": "Electrician IBEW Local 3",
                    "headcount": 45,
                    "labor_cost": 6300000.0,
                    "start_date": "2027-06-01",
                    "end_date": "2029-01-31",
                },
                {
                    "phase_name": "MEP Rough-In & Vertical Risers",
                    "crew_name": "J.C. Higgins Mechanical (Hassan Rahman, Foreman)",
                    "skill_type": "Steamfitter Local 638",
                    "headcount": 38,
                    "labor_cost": 5100000.0,
                    "start_date": "2027-06-01",
                    "end_date": "2029-01-31",
                },
                {
                    "phase_name": "Concrete",
                    "crew_name": "Navillus Concrete (Maria Flores, Superintendent)",
                    "skill_type": "Laborer/Cement Mason Local 6A",
                    "headcount": 55,
                    "labor_cost": 5500000.0,
                    "start_date": "2026-04-01",
                    "end_date": "2028-01-31",
                },
            ],
            "workforce_gaps": [
                {"role": "Certified Welder (AWS D1.1)", "shortage": "8 welders — critical path steel erection pace"},
                {"role": "Tower Crane Operator (CCO certified)", "shortage": "1 operator for Crane #3 mobilization Q1-2027"},
                {"role": "BIM/VDC Coordinator", "shortage": "2 coordinators for MEP clash resolution backlog"},
            ],
        },
    })


# ---------------------------------------------------------------------------
# Project 2: Hyperscale Data Center Campus — Loudoun County, VA
# ---------------------------------------------------------------------------


def _ashburn_datacenter_fixture() -> dict[str, Any]:
    return _attach_building_definition({
        "projectSummary": {
            "project_name": "Ashburn Data Center Campus — Halls A through D",
            "client_name": "CloudScale Infrastructure Inc. (Tenant: AWS)",
            "location": "44900 Prentice Drive, Ashburn, VA 20147",
            "project_type": "Hyperscale Data Center (4-Hall Campus)",
            "budget": 1850000000,
            "duration_months": 30,
            "scope": (
                "Four data center halls (48 MW total critical IT load), each 250,000 SF "
                "with N+1 redundant UPS and cooling. 2N utility feed from Dominion Energy "
                "(230kV to 13.8kV step-down). Tier III+ design. On-site diesel generator "
                "farm (56 × 3MW CAT 3516C), chilled water plant with adiabatic coolers, "
                "and 12-acre secured campus with perimeter fencing, mantrap, and vehicle "
                "barriers."
            ),
            "square_footage": 1000000,
            "floor_count": 2,
            "complexity_level": "High",
            "start_date": "2025-11-01",
            "target_completion_date": "2028-05-01",
            "milestones": [
                {"name": "Notice to Proceed", "date": "2025-11-01"},
                {"name": "Mass Grading Complete", "date": "2026-03-15"},
                {"name": "Hall A Shell Complete", "date": "2026-10-31"},
                {"name": "Hall A Energization (48hr load bank)", "date": "2027-04-15"},
                {"name": "Hall A Tenant Handover", "date": "2027-06-01"},
                {"name": "Hall B Tenant Handover", "date": "2027-10-01"},
                {"name": "Hall C Tenant Handover", "date": "2028-01-15"},
                {"name": "Hall D Tenant Handover & Campus Complete", "date": "2028-05-01"},
            ],
        },
        "blueprintSummary": {
            "construction_type": "Pre-Engineered Steel Frame with concrete tilt-up shell",
            "stories_above_grade": 2,
            "stories_below_grade": 0,
            "structural_steel_tons": 9800,
            "concrete_cy": 78000,
            "lateral_system": "Braced steel frames with concrete shear panels",
            "foundation_type": "Spread footings on compacted structural fill",
            "mep_highlights": {
                "critical_it_load_mw": 48,
                "utility_service_kv": 230,
                "generators": 56,
                "generator_model": "CAT 3516C (3MW each)",
                "ups_systems": 16,
                "ups_model": "Vertiv Liebert EXL S1 (1500 kVA)",
                "cooling_tons": 14400,
                "raised_floor_sf": 720000,
            },
        },
        "permitAssessment": {
            "required_permits": [
                {
                    "name": "Loudoun County Site Plan Approval",
                    "category": "Municipal — Land Use",
                    "status": "Approved",
                    "estimated_days": 0,
                },
                {
                    "name": "Building Permit (Halls A–D, Generator Yard)",
                    "category": "Municipal — Loudoun County DTCI",
                    "status": "Approved",
                    "estimated_days": 0,
                },
                {
                    "name": "Dominion Energy Interconnection Agreement",
                    "category": "Utility — Dominion Virginia Power",
                    "status": "Approved",
                    "estimated_days": 0,
                },
                {
                    "name": "Virginia DEQ Stormwater VSMP Permit",
                    "category": "State — Environmental",
                    "status": "Approved",
                    "estimated_days": 0,
                },
                {
                    "name": "Loudoun County Fire Marshal — Diesel Storage Permit",
                    "category": "Life Safety — Fire Marshal",
                    "status": "In Review",
                    "estimated_days": 14,
                },
                {
                    "name": "Air Quality Permit (56 generators, >100 TPY NOx)",
                    "category": "State — VA DEQ Air Division",
                    "status": "Pending",
                    "estimated_days": 45,
                },
            ]
        },
        "projectPlan": {
            "estimated_duration_days": 912,
            "project_phases": [
                {
                    "name": "Mass Grading & Utilities",
                    "status": "completed",
                    "start_date": "2025-11-01",
                    "end_date": "2026-03-15",
                    "progress": 100,
                },
                {
                    "name": "Foundations & Slab-on-Grade (All Halls)",
                    "status": "completed",
                    "start_date": "2026-02-01",
                    "end_date": "2026-07-31",
                    "progress": 100,
                },
                {
                    "name": "Steel Erection & Tilt-Up Panels",
                    "status": "in-progress",
                    "start_date": "2026-05-15",
                    "end_date": "2026-12-31",
                    "progress": 70,
                },
                {
                    "name": "Roofing & Building Envelope",
                    "status": "in-progress",
                    "start_date": "2026-08-01",
                    "end_date": "2027-02-28",
                    "progress": 40,
                },
                {
                    "name": "Electrical Infrastructure (MSB, PDUs, UPS)",
                    "status": "in-progress",
                    "start_date": "2026-09-01",
                    "end_date": "2027-08-31",
                    "progress": 25,
                },
                {
                    "name": "Mechanical Plant (Chillers, Piping, CRAHs)",
                    "status": "pending",
                    "start_date": "2026-11-01",
                    "end_date": "2027-09-30",
                    "progress": 5,
                },
                {
                    "name": "Generator Farm & Fuel System",
                    "status": "pending",
                    "start_date": "2027-01-01",
                    "end_date": "2027-06-30",
                    "progress": 0,
                },
                {
                    "name": "Integrated Systems Testing (IST)",
                    "status": "pending",
                    "start_date": "2027-03-01",
                    "end_date": "2028-03-31",
                    "progress": 0,
                },
                {
                    "name": "Commissioning & Tenant Handover",
                    "status": "pending",
                    "start_date": "2027-05-01",
                    "end_date": "2028-05-01",
                    "progress": 0,
                },
            ],
            "materials": [
                {"material_name": "Structural Steel (PEMB frames + mezzanine)", "quantity": 9800, "unit": "TON"},
                {"material_name": "Concrete (SOG 6\" reinforced, footings, walls)", "quantity": 78000, "unit": "CY"},
                {"material_name": "Medium Voltage Switchgear (15kV)", "quantity": 32, "unit": "EA"},
                {"material_name": "UPS Units (Vertiv 1500 kVA)", "quantity": 16, "unit": "EA"},
                {"material_name": "Diesel Generators (CAT 3516C, 3MW)", "quantity": 56, "unit": "EA"},
                {"material_name": "CRAH Units (Vertiv Liebert DSE 165kW)", "quantity": 384, "unit": "EA"},
                {"material_name": "Raised Access Floor Tiles (PSA 2500lb)", "quantity": 720000, "unit": "SF"},
                {"material_name": "750 MCM Copper Power Cable", "quantity": 480000, "unit": "LF"},
            ],
            "inspection_stages": [
                {"name": "SOG flatness (FF/FL) testing per ACI 117", "phase": "Foundations", "status": "passed"},
                {"name": "Structural steel bolt torque (TC bolts)", "phase": "Steel Erection", "status": "in-progress"},
                {"name": "Roofing warranty inspection (60-mil TPO)", "phase": "Envelope", "status": "planned"},
                {"name": "MV switchgear hi-pot test (15kV)", "phase": "Electrical", "status": "planned"},
                {"name": "UPS module acceptance test (full load)", "phase": "Electrical", "status": "planned"},
                {"name": "Generator 2-hour load bank test (per NFPA 110)", "phase": "Generators", "status": "planned"},
                {"name": "Chilled water hydronic system pressure test", "phase": "Mechanical", "status": "planned"},
                {"name": "Level 5 IST (full facility failover simulation)", "phase": "Commissioning", "status": "planned"},
            ],
            "dependencies": [
                {"predecessor": "Mass Grading & Utilities", "successor": "Foundations & Slab-on-Grade (All Halls)"},
                {"predecessor": "Foundations & Slab-on-Grade (All Halls)", "successor": "Steel Erection & Tilt-Up Panels"},
                {"predecessor": "Steel Erection & Tilt-Up Panels", "successor": "Roofing & Building Envelope"},
                {"predecessor": "Steel Erection & Tilt-Up Panels", "successor": "Electrical Infrastructure (MSB, PDUs, UPS)"},
                {"predecessor": "Roofing & Building Envelope", "successor": "Mechanical Plant (Chillers, Piping, CRAHs)"},
                {"predecessor": "Electrical Infrastructure (MSB, PDUs, UPS)", "successor": "Integrated Systems Testing (IST)"},
                {"predecessor": "Mechanical Plant (Chillers, Piping, CRAHs)", "successor": "Integrated Systems Testing (IST)"},
                {"predecessor": "Generator Farm & Fuel System", "successor": "Integrated Systems Testing (IST)"},
                {"predecessor": "Integrated Systems Testing (IST)", "successor": "Commissioning & Tenant Handover"},
            ],
        },
        "supplierAnalysis": {
            "procurement_plan": [
                {
                    "material_name": "Diesel Generators — CAT 3516C (3MW, 480V, EPA Tier 4F)",
                    "supplier_name": "Caterpillar / Carter Machinery (VA dealer)",
                    "quantity": 56,
                    "unit_price": 1450000.00,
                    "delivery_date": "2027-01-15",
                    "total_cost": 81200000.0,
                    "lead_time_weeks": 40,
                },
                {
                    "material_name": "UPS Systems — Vertiv Liebert EXL S1 1500 kVA (N+1)",
                    "supplier_name": "Vertiv / Wesco International",
                    "quantity": 16,
                    "unit_price": 625000.00,
                    "delivery_date": "2026-11-01",
                    "total_cost": 10000000.0,
                    "lead_time_weeks": 28,
                },
                {
                    "material_name": "Medium Voltage Switchgear (Eaton VCP-W 15kV)",
                    "supplier_name": "Eaton Corporation / Graybar Electric",
                    "quantity": 32,
                    "unit_price": 285000.00,
                    "delivery_date": "2026-09-15",
                    "total_cost": 9120000.0,
                    "lead_time_weeks": 32,
                },
                {
                    "material_name": "CRAH Units — Vertiv Liebert DSE 165kW (EC fan, glycol)",
                    "supplier_name": "Vertiv / Data Aire Rep",
                    "quantity": 384,
                    "unit_price": 78000.00,
                    "delivery_date": "2027-02-01",
                    "total_cost": 29952000.0,
                    "lead_time_weeks": 24,
                },
                {
                    "material_name": "Raised Access Floor (Tate ConCore 2500lb PSA, HPL finish)",
                    "supplier_name": "Tate Access Floors / Kingspan",
                    "quantity": 720000,
                    "unit_price": 14.50,
                    "delivery_date": "2027-01-01",
                    "total_cost": 10440000.0,
                    "lead_time_weeks": 12,
                },
            ],
            "supply_chain_risks": [
                {
                    "risk": "Generator delivery delay — global demand for hyperscale gensets exceeds CAT production capacity",
                    "severity": "Critical",
                    "mitigation": "Firm PO placed 14 months ahead; accept staged delivery (14 units/quarter); identify MTU as alternate",
                },
                {
                    "risk": "750 MCM copper cable price volatility (COMEX copper at $4.80/lb)",
                    "severity": "High",
                    "mitigation": "Hedged 60% of copper tonnage via commodity forward contract; remainder at spot with 10% contingency",
                },
                {
                    "risk": "UPS battery modules (lithium-ion) lead time stretch",
                    "severity": "Medium",
                    "mitigation": "Pre-ordered battery strings; approved VRLA as interim if Li-ion delayed >6 weeks",
                },
            ],
        },
        "crewAnalysis": {
            "crew_allocations": [
                {
                    "phase_name": "Electrical Infrastructure",
                    "crew_name": "M.C. Dean — Critical Power Division (James Park, PM)",
                    "skill_type": "Electrician (IBEW Local 26)",
                    "headcount": 85,
                    "labor_cost": 12750000.0,
                    "start_date": "2026-09-01",
                    "end_date": "2027-08-31",
                },
                {
                    "phase_name": "Mechanical Plant",
                    "crew_name": "Southland Industries — Piping Crew (Victor Nguyen, Superintendent)",
                    "skill_type": "Pipefitter (UA Local 602)",
                    "headcount": 42,
                    "labor_cost": 5460000.0,
                    "start_date": "2026-11-01",
                    "end_date": "2027-09-30",
                },
                {
                    "phase_name": "Steel Erection & Tilt-Up Panels",
                    "crew_name": "Hensel Phelps — Structure Crew (Carlos Rivera, Superintendent)",
                    "skill_type": "Ironworker / Operator",
                    "headcount": 35,
                    "labor_cost": 4200000.0,
                    "start_date": "2026-05-15",
                    "end_date": "2026-12-31",
                },
                {
                    "phase_name": "Integrated Systems Testing",
                    "crew_name": "Cx Associates — Commissioning Team (Rachel Kim, Lead CxA)",
                    "skill_type": "Commissioning Agent (ASHRAE certified)",
                    "headcount": 12,
                    "labor_cost": 1800000.0,
                    "start_date": "2027-03-01",
                    "end_date": "2028-03-31",
                },
            ],
            "workforce_gaps": [
                {"role": "Licensed Electrician (Journeyman, VA)", "shortage": "12 electricians for MV termination surge in Q2-2027"},
                {"role": "Controls Technician (BMS/EPMS)", "shortage": "4 technicians — integration testing phase"},
            ],
        },
    })


# ---------------------------------------------------------------------------
# Project 3: Luxury Waterfront Condominium — Miami Beach, FL
# ---------------------------------------------------------------------------


def _miami_condo_fixture() -> dict[str, Any]:
    return _attach_building_definition({
        "projectSummary": {
            "project_name": "Oceana Residences — 57-Story Luxury Condominium",
            "client_name": "Terra Group & Crescent Heights Development",
            "location": "8701 Collins Avenue, Miami Beach, FL 33154",
            "project_type": "Luxury Residential High-Rise Condominium",
            "budget": 890000000,
            "duration_months": 36,
            "scope": (
                "57-story oceanfront luxury condominium tower with 120 residences "
                "(2,400–8,500 SF), 4 penthouses, 12-story parking podium, resort-level "
                "amenity deck (pool, spa, fitness, theater), private marina berths. "
                "Post-tensioned concrete flat-plate structure, hurricane-rated impact "
                "glazing system (Miami-Dade NOA approved), and high-velocity hurricane "
                "zone (HVHZ) construction throughout."
            ),
            "square_footage": 980000,
            "floor_count": 57,
            "complexity_level": "High",
            "start_date": "2025-06-01",
            "target_completion_date": "2028-06-01",
            "milestones": [
                {"name": "Notice to Proceed", "date": "2025-06-01"},
                {"name": "Auger-Cast Pile Foundation Complete", "date": "2025-11-30"},
                {"name": "Parking Podium Topping Out", "date": "2026-06-30"},
                {"name": "Tower Topping Out (Level 57)", "date": "2027-09-15"},
                {"name": "Facade Substantial Completion", "date": "2028-01-31"},
                {"name": "TCO — Amenity + Floors 13–35", "date": "2028-03-15"},
                {"name": "Final CO — Full Building", "date": "2028-06-01"},
            ],
        },
        "blueprintSummary": {
            "construction_type": "Type I-A, HVHZ (High Velocity Hurricane Zone)",
            "stories_above_grade": 57,
            "stories_below_grade": 2,
            "structural_steel_tons": 1800,
            "concrete_cy": 92000,
            "curtain_wall_sf": 340000,
            "lateral_system": "Post-tensioned flat plate with shear walls & coupled core",
            "foundation_type": "768 auger-cast piles to limestone bearing at -65 ft",
            "mep_highlights": {
                "electrical_service_amps": 16000,
                "elevators": 14,
                "cooling_tons": 3200,
                "emergency_generators_kw": 4500,
                "domestic_water_booster_hp": 150,
            },
        },
        "permitAssessment": {
            "required_permits": [
                {
                    "name": "Miami-Dade County Building Permit (Master)",
                    "category": "Municipal — Miami-Dade DERM",
                    "status": "Approved",
                    "estimated_days": 0,
                    "permit_number": "BD-2025-017823",
                },
                {
                    "name": "Coastal Construction Control Line (CCCL) Permit",
                    "category": "State — FL DEP",
                    "status": "Approved",
                    "estimated_days": 0,
                },
                {
                    "name": "DERM Dewatering Permit",
                    "category": "Environmental — Groundwater",
                    "status": "Approved",
                    "estimated_days": 0,
                },
                {
                    "name": "Miami-Dade NOA Approval — Impact Glazing System",
                    "category": "Product Approval — HVHZ",
                    "status": "Approved",
                    "estimated_days": 0,
                    "permit_number": "NOA-21-0453.07",
                },
                {
                    "name": "Army Corps of Engineers (USACE) — Marina Berth Permit",
                    "category": "Federal — Waterway",
                    "status": "In Review",
                    "estimated_days": 60,
                },
                {
                    "name": "Threshold Building Inspection Program Registration",
                    "category": "State — FL Statute 553.79",
                    "status": "Approved",
                    "estimated_days": 0,
                },
            ]
        },
        "projectPlan": {
            "estimated_duration_days": 1096,
            "project_phases": [
                {
                    "name": "Site Prep & Auger-Cast Piling",
                    "status": "completed",
                    "start_date": "2025-06-01",
                    "end_date": "2025-11-30",
                    "progress": 100,
                },
                {
                    "name": "Below-Grade Structure & Podium",
                    "status": "completed",
                    "start_date": "2025-10-01",
                    "end_date": "2026-06-30",
                    "progress": 100,
                },
                {
                    "name": "Tower Vertical Construction (PT slab cycle)",
                    "status": "in-progress",
                    "start_date": "2026-04-01",
                    "end_date": "2027-09-15",
                    "progress": 55,
                },
                {
                    "name": "Facade / Impact Glazing Installation",
                    "status": "in-progress",
                    "start_date": "2026-10-01",
                    "end_date": "2028-01-31",
                    "progress": 30,
                },
                {
                    "name": "MEP Rough-In (following structure by 8 floors)",
                    "status": "in-progress",
                    "start_date": "2026-08-01",
                    "end_date": "2027-12-31",
                    "progress": 35,
                },
                {
                    "name": "Interior Finishes & Unit Fit-Out",
                    "status": "pending",
                    "start_date": "2027-04-01",
                    "end_date": "2028-04-30",
                    "progress": 5,
                },
                {
                    "name": "Amenity Deck & Pool Construction",
                    "status": "pending",
                    "start_date": "2027-06-01",
                    "end_date": "2028-02-28",
                    "progress": 0,
                },
                {
                    "name": "Elevator Installation & Inspection",
                    "status": "pending",
                    "start_date": "2027-02-01",
                    "end_date": "2028-03-31",
                    "progress": 0,
                },
                {
                    "name": "Commissioning & Closeout",
                    "status": "pending",
                    "start_date": "2028-02-01",
                    "end_date": "2028-06-01",
                    "progress": 0,
                },
            ],
            "materials": [
                {"material_name": "Post-Tensioned Strand (0.6\" dia, 270 ksi)", "quantity": 2400000, "unit": "LF"},
                {"material_name": "Ready-Mix Concrete (6000 psi, marine aggregate)", "quantity": 92000, "unit": "CY"},
                {"material_name": "Impact-Rated Glazing Units (Miami-Dade NOA)", "quantity": 4200, "unit": "EA"},
                {"material_name": "Italian Porcelain Tile (units, lobby)", "quantity": 185000, "unit": "SF"},
                {"material_name": "Sub-Zero/Wolf Appliance Packages", "quantity": 124, "unit": "SET"},
                {"material_name": "Auger-Cast Piles (18\" dia, 65 ft)", "quantity": 768, "unit": "EA"},
            ],
            "inspection_stages": [
                {"name": "Pile integrity testing (low-strain PIT)", "phase": "Foundation", "status": "passed"},
                {"name": "PT strand stressing verification (each pour cycle)", "phase": "Structure", "status": "in-progress"},
                {"name": "Threshold inspector special inspection (FL statute)", "phase": "Structure", "status": "in-progress"},
                {"name": "Impact glazing large-missile test certification", "phase": "Facade", "status": "passed"},
                {"name": "HVHZ roofing inspection (FBC Section 1523)", "phase": "Roofing", "status": "planned"},
                {"name": "Fire pump acceptance test (NFPA 20)", "phase": "Life Safety", "status": "planned"},
                {"name": "Pool health department inspection", "phase": "Amenity", "status": "planned"},
            ],
            "dependencies": [
                {"predecessor": "Site Prep & Auger-Cast Piling", "successor": "Below-Grade Structure & Podium"},
                {"predecessor": "Below-Grade Structure & Podium", "successor": "Tower Vertical Construction (PT slab cycle)"},
                {"predecessor": "Tower Vertical Construction (PT slab cycle)", "successor": "Facade / Impact Glazing Installation"},
                {"predecessor": "Tower Vertical Construction (PT slab cycle)", "successor": "MEP Rough-In (following structure by 8 floors)"},
                {"predecessor": "MEP Rough-In (following structure by 8 floors)", "successor": "Interior Finishes & Unit Fit-Out"},
                {"predecessor": "Facade / Impact Glazing Installation", "successor": "Interior Finishes & Unit Fit-Out"},
                {"predecessor": "Interior Finishes & Unit Fit-Out", "successor": "Commissioning & Closeout"},
            ],
        },
        "supplierAnalysis": {
            "procurement_plan": [
                {
                    "material_name": "Impact Glazing System — Guardian SunGuard HP Neutral 41/22 (HVHZ)",
                    "supplier_name": "Guardian Glass / YKK AP America (fabricator)",
                    "quantity": 4200,
                    "unit_price": 2400.00,
                    "delivery_date": "2026-09-01",
                    "total_cost": 10080000.0,
                    "lead_time_weeks": 26,
                },
                {
                    "material_name": "Post-Tension Strand (0.6\", 270 ksi, unbonded)",
                    "supplier_name": "Suncoast Post-Tension Ltd.",
                    "quantity": 2400000,
                    "unit_price": 0.48,
                    "delivery_date": "2026-03-15",
                    "total_cost": 1152000.0,
                    "lead_time_weeks": 6,
                },
                {
                    "material_name": "Ready-Mix Concrete (6000 psi, chloride-resistant)",
                    "supplier_name": "CEMEX Southeast",
                    "quantity": 92000,
                    "unit_price": 178.00,
                    "delivery_date": "2025-10-01",
                    "total_cost": 16376000.0,
                    "lead_time_weeks": 1,
                },
                {
                    "material_name": "Sub-Zero / Wolf Premium Appliance Packages",
                    "supplier_name": "Sub-Zero Group Inc. / Ferguson Enterprise",
                    "quantity": 124,
                    "unit_price": 85000.00,
                    "delivery_date": "2027-06-01",
                    "total_cost": 10540000.0,
                    "lead_time_weeks": 20,
                },
                {
                    "material_name": "Elevators — Schindler 7000 (high-speed, destination dispatch)",
                    "supplier_name": "Schindler Elevator Corporation",
                    "quantity": 14,
                    "unit_price": 520000.00,
                    "delivery_date": "2027-01-15",
                    "total_cost": 7280000.0,
                    "lead_time_weeks": 44,
                },
            ],
            "supply_chain_risks": [
                {
                    "risk": "Hurricane season (Jun–Nov) may halt tower crane operations and exterior work 2–4 weeks/yr",
                    "severity": "High",
                    "mitigation": "Schedule aggressive pours in dry season; crane tie-down protocol at 75 mph forecast",
                },
                {
                    "risk": "Italian tile shipment delays due to Mediterranean freight congestion",
                    "severity": "Medium",
                    "mitigation": "Order 18 months before install; accept domestic alternate (Crossville) for common areas",
                },
                {
                    "risk": "Marine aggregate concrete supply constrained by dredge permitting",
                    "severity": "Low",
                    "mitigation": "Approved alternate aggregate source from Martin Marietta quarry",
                },
            ],
        },
        "crewAnalysis": {
            "crew_allocations": [
                {
                    "phase_name": "Tower Vertical Construction",
                    "crew_name": "Coastal Concrete — PT Slab Crew (Jorge Ramirez, Superintendent)",
                    "skill_type": "Concrete Finisher / PT Installer",
                    "headcount": 62,
                    "labor_cost": 8680000.0,
                    "start_date": "2026-04-01",
                    "end_date": "2027-09-15",
                },
                {
                    "phase_name": "Facade / Impact Glazing",
                    "crew_name": "Enclos Corporation (Mark Thompson, Project Manager)",
                    "skill_type": "Glazier / Curtain Wall Installer",
                    "headcount": 28,
                    "labor_cost": 4200000.0,
                    "start_date": "2026-10-01",
                    "end_date": "2028-01-31",
                },
                {
                    "phase_name": "MEP Rough-In",
                    "crew_name": "Poole & Kent — Mechanical (Andres Silva, Foreman)",
                    "skill_type": "Plumber / Pipefitter (UA Local 725)",
                    "headcount": 34,
                    "labor_cost": 4760000.0,
                    "start_date": "2026-08-01",
                    "end_date": "2027-12-31",
                },
                {
                    "phase_name": "Interior Finishes",
                    "crew_name": "Moss CM — Finish Trades (Diana Torres, Superintendent)",
                    "skill_type": "Carpenter / Tile Setter",
                    "headcount": 75,
                    "labor_cost": 9000000.0,
                    "start_date": "2027-04-01",
                    "end_date": "2028-04-30",
                },
            ],
            "workforce_gaps": [
                {"role": "PT Stressing Technician (PTI certified)", "shortage": "3 technicians for peak tower cycle pace"},
                {"role": "Finish Carpenter (luxury residential)", "shortage": "8 carpenters — Italian cabinetry install"},
            ],
        },
    })


# ---------------------------------------------------------------------------
# Project 4: University Science Research Building — Boston, MA
# ---------------------------------------------------------------------------


def _boston_research_fixture() -> dict[str, Any]:
    return _attach_building_definition({
        "projectSummary": {
            "project_name": "MIT Building 58 — Interdisciplinary Science Complex",
            "client_name": "Massachusetts Institute of Technology",
            "location": "292 Main Street, Cambridge, MA 02142",
            "project_type": "Higher Education — Research Laboratory",
            "budget": 465000000,
            "duration_months": 32,
            "scope": (
                "8-story, 320,000 GSF interdisciplinary science research building housing "
                "wet labs (BSL-2/BSL-3), dry computational labs, cleanroom (ISO 5/6), "
                "vivarium (AAALAC accredited), and collaborative learning commons. "
                "Vibration-sensitive research floors on isolated foundation. LEED Platinum "
                "target with district steam connection and 2.4 MW rooftop solar + battery."
            ),
            "square_footage": 320000,
            "floor_count": 8,
            "complexity_level": "High",
            "start_date": "2025-08-15",
            "target_completion_date": "2028-04-15",
            "milestones": [
                {"name": "Notice to Proceed", "date": "2025-08-15"},
                {"name": "Excavation Support Installation", "date": "2025-12-15"},
                {"name": "Foundation & Vibration Isolation Complete", "date": "2026-05-31"},
                {"name": "Structural Topping Out", "date": "2027-02-28"},
                {"name": "Lab Casework & Fume Hood Installation", "date": "2027-10-31"},
                {"name": "Cleanroom Certification", "date": "2028-01-15"},
                {"name": "Substantial Completion", "date": "2028-03-01"},
                {"name": "Occupancy & Move-In", "date": "2028-04-15"},
            ],
        },
        "blueprintSummary": {
            "construction_type": "Type I-B (Concrete frame with steel roof)",
            "stories_above_grade": 8,
            "stories_below_grade": 2,
            "structural_steel_tons": 3200,
            "concrete_cy": 38000,
            "curtain_wall_sf": 86000,
            "lateral_system": "Concrete moment frames + shear walls (vibration-isolated at L1–L3)",
            "foundation_type": "Drilled shafts to Cambridge argillite bedrock, vibration isolation pads",
            "mep_highlights": {
                "lab_air_changes_per_hour": 12,
                "fume_hoods": 186,
                "bsl3_containment_rooms": 4,
                "cleanroom_sf": 8500,
                "emergency_generators_kw": 3200,
                "cooling_tons": 2400,
                "lab_exhaust_cfm": 285000,
            },
        },
        "permitAssessment": {
            "required_permits": [
                {
                    "name": "Cambridge Inspectional Services — Building Permit",
                    "category": "Municipal — City of Cambridge",
                    "status": "Approved",
                    "estimated_days": 0,
                    "permit_number": "BP-2025-002847",
                },
                {
                    "name": "Cambridge Historical Commission Review (advisory)",
                    "category": "Municipal — Historic Preservation",
                    "status": "Approved",
                    "estimated_days": 0,
                },
                {
                    "name": "MA DEP Chapter 91 Waterway License (Charles River proximity)",
                    "category": "State — Environmental",
                    "status": "Approved",
                    "estimated_days": 0,
                },
                {
                    "name": "BSL-3 Lab Registration — CDC/USDA Select Agent Program",
                    "category": "Federal — CDC/APHIS",
                    "status": "In Review",
                    "estimated_days": 90,
                },
                {
                    "name": "NRC Radioactive Materials License Amendment",
                    "category": "Federal — Nuclear Regulatory Commission",
                    "status": "Pending",
                    "estimated_days": 120,
                },
                {
                    "name": "Cambridge DPW Sewer Connection Permit",
                    "category": "Municipal — Utilities",
                    "status": "Approved",
                    "estimated_days": 0,
                },
                {
                    "name": "MADEP Air Quality Plan Approval (lab exhaust)",
                    "category": "State — Air Quality",
                    "status": "Approved",
                    "estimated_days": 0,
                },
            ]
        },
        "projectPlan": {
            "estimated_duration_days": 975,
            "project_phases": [
                {
                    "name": "Demolition & Excavation Support",
                    "status": "completed",
                    "start_date": "2025-08-15",
                    "end_date": "2025-12-15",
                    "progress": 100,
                },
                {
                    "name": "Foundation & Vibration Isolation System",
                    "status": "completed",
                    "start_date": "2025-11-01",
                    "end_date": "2026-05-31",
                    "progress": 100,
                },
                {
                    "name": "Concrete Superstructure",
                    "status": "in-progress",
                    "start_date": "2026-03-01",
                    "end_date": "2027-02-28",
                    "progress": 60,
                },
                {
                    "name": "Building Envelope & Curtain Wall",
                    "status": "in-progress",
                    "start_date": "2026-09-01",
                    "end_date": "2027-06-30",
                    "progress": 25,
                },
                {
                    "name": "MEP Rough-In & Lab Infrastructure",
                    "status": "in-progress",
                    "start_date": "2026-08-01",
                    "end_date": "2027-09-30",
                    "progress": 20,
                },
                {
                    "name": "Cleanroom Construction (ISO 5/6)",
                    "status": "pending",
                    "start_date": "2027-05-01",
                    "end_date": "2028-01-15",
                    "progress": 0,
                },
                {
                    "name": "Lab Casework, Fume Hoods & Equipment",
                    "status": "pending",
                    "start_date": "2027-06-01",
                    "end_date": "2027-12-31",
                    "progress": 0,
                },
                {
                    "name": "BSL-3 Suite Construction & Certification",
                    "status": "pending",
                    "start_date": "2027-07-01",
                    "end_date": "2028-02-28",
                    "progress": 0,
                },
                {
                    "name": "Commissioning, LEED Cert & Occupancy",
                    "status": "pending",
                    "start_date": "2027-12-01",
                    "end_date": "2028-04-15",
                    "progress": 0,
                },
            ],
            "materials": [
                {"material_name": "Reinforced Concrete (5000 psi, low-vibration mix)", "quantity": 38000, "unit": "CY"},
                {"material_name": "Structural Steel (roof trusses, mezzanines)", "quantity": 3200, "unit": "TON"},
                {"material_name": "Lab-Grade Epoxy Resin Countertops", "quantity": 12400, "unit": "LF"},
                {"material_name": "Fume Hoods (constant-volume, perchloric-rated)", "quantity": 186, "unit": "EA"},
                {"material_name": "HEPA Filter Modules (BSL-3 exhaust)", "quantity": 64, "unit": "EA"},
                {"material_name": "Vibration Isolation Spring Assemblies", "quantity": 420, "unit": "EA"},
                {"material_name": "Cleanroom Wall Panels (flush-mount, steel-faced)", "quantity": 8500, "unit": "SF"},
                {"material_name": "Lab Gas Piping (SS 316L, orbital-welded)", "quantity": 24000, "unit": "LF"},
            ],
            "inspection_stages": [
                {"name": "Vibration isolation system field acceptance (VC-D criteria)", "phase": "Foundation", "status": "passed"},
                {"name": "Concrete core test (56-day strength verification)", "phase": "Structure", "status": "in-progress"},
                {"name": "Cleanroom particle count certification (ISO 14644)", "phase": "Cleanroom", "status": "planned"},
                {"name": "BSL-3 containment verification (CDC/NIH guidelines)", "phase": "BSL-3 Suite", "status": "planned"},
                {"name": "Fume hood face velocity test (ASHRAE 110)", "phase": "Lab Casework", "status": "planned"},
                {"name": "Lab exhaust stack dispersion modeling validation", "phase": "MEP", "status": "planned"},
                {"name": "Emergency generator load test (NFPA 110, Level 1)", "phase": "MEP", "status": "planned"},
                {"name": "LEED Platinum documentation audit", "phase": "Commissioning", "status": "planned"},
            ],
            "dependencies": [
                {"predecessor": "Demolition & Excavation Support", "successor": "Foundation & Vibration Isolation System"},
                {"predecessor": "Foundation & Vibration Isolation System", "successor": "Concrete Superstructure"},
                {"predecessor": "Concrete Superstructure", "successor": "Building Envelope & Curtain Wall"},
                {"predecessor": "Concrete Superstructure", "successor": "MEP Rough-In & Lab Infrastructure"},
                {"predecessor": "Building Envelope & Curtain Wall", "successor": "Cleanroom Construction (ISO 5/6)"},
                {"predecessor": "MEP Rough-In & Lab Infrastructure", "successor": "Lab Casework, Fume Hoods & Equipment"},
                {"predecessor": "MEP Rough-In & Lab Infrastructure", "successor": "BSL-3 Suite Construction & Certification"},
                {"predecessor": "BSL-3 Suite Construction & Certification", "successor": "Commissioning, LEED Cert & Occupancy"},
            ],
        },
        "supplierAnalysis": {
            "procurement_plan": [
                {
                    "material_name": "Lab Fume Hoods — Hamilton SafeAire II (6ft, constant volume)",
                    "supplier_name": "Hamilton Scientific / Fisher Scientific",
                    "quantity": 186,
                    "unit_price": 14500.00,
                    "delivery_date": "2027-05-01",
                    "total_cost": 2697000.0,
                    "lead_time_weeks": 18,
                },
                {
                    "material_name": "Cleanroom Panels — Kingspan KS1000 AWP (flush, 4\" steel)",
                    "supplier_name": "Kingspan Insulated Panels / Cleanroom Solutions Inc.",
                    "quantity": 8500,
                    "unit_price": 85.00,
                    "delivery_date": "2027-04-15",
                    "total_cost": 722500.0,
                    "lead_time_weeks": 14,
                },
                {
                    "material_name": "Vibration Isolation Springs — Kinetics Noise Control RIM-300",
                    "supplier_name": "Kinetics Noise Control Inc.",
                    "quantity": 420,
                    "unit_price": 3200.00,
                    "delivery_date": "2025-10-15",
                    "total_cost": 1344000.0,
                    "lead_time_weeks": 10,
                },
                {
                    "material_name": "BSL-3 Autoclave — Fedegari FOB5",
                    "supplier_name": "Fedegari Autoclavi SpA / US Agent",
                    "quantity": 4,
                    "unit_price": 185000.00,
                    "delivery_date": "2027-06-01",
                    "total_cost": 740000.0,
                    "lead_time_weeks": 32,
                },
                {
                    "material_name": "Emergency Diesel Generators (Cummins QSK60, 2MW)",
                    "supplier_name": "Cummins Inc. / F.W. Webb",
                    "quantity": 2,
                    "unit_price": 980000.00,
                    "delivery_date": "2026-12-01",
                    "total_cost": 1960000.0,
                    "lead_time_weeks": 30,
                },
            ],
            "supply_chain_risks": [
                {
                    "risk": "BSL-3 autoclave — single Italian manufacturer with 8-month lead time",
                    "severity": "High",
                    "mitigation": "PO placed 12 months early; Getinge as approved alternate if delivery slips > 4 weeks",
                },
                {
                    "risk": "Lab casework epoxy resin supply shortage (post-COVID demand surge in pharma sector)",
                    "severity": "Medium",
                    "mitigation": "Secured allocation with Durcon; phenolic resin approved as alternate for non-chemical areas",
                },
                {
                    "risk": "Curtain wall aluminum extrusion availability (Kawneer 1600UT series)",
                    "severity": "Low",
                    "mitigation": "Material on site; long-lead extrusion order placed Q1-2026",
                },
            ],
        },
        "crewAnalysis": {
            "crew_allocations": [
                {
                    "phase_name": "Concrete Superstructure",
                    "crew_name": "Suffolk Construction — Concrete Div. (Sean Murphy, Superintendent)",
                    "skill_type": "Carpenter/Ironworker (Laborers Local 22)",
                    "headcount": 48,
                    "labor_cost": 6240000.0,
                    "start_date": "2026-03-01",
                    "end_date": "2027-02-28",
                },
                {
                    "phase_name": "MEP Rough-In & Lab Infrastructure",
                    "crew_name": "J.C. Cannistraro — Mechanical (Raj Patel, PM)",
                    "skill_type": "Pipefitter (UA Local 537)",
                    "headcount": 38,
                    "labor_cost": 5320000.0,
                    "start_date": "2026-08-01",
                    "end_date": "2027-09-30",
                },
                {
                    "phase_name": "Cleanroom Construction",
                    "crew_name": "Cleanroom Solutions Inc. (Terry Wallace, Lead)",
                    "skill_type": "Cleanroom Specialist",
                    "headcount": 16,
                    "labor_cost": 2400000.0,
                    "start_date": "2027-05-01",
                    "end_date": "2028-01-15",
                },
                {
                    "phase_name": "BSL-3 Suite Construction",
                    "crew_name": "CRB Group — Containment Build (Dr. Amy Chen, QA)",
                    "skill_type": "Biocontainment Construction Specialist",
                    "headcount": 12,
                    "labor_cost": 2160000.0,
                    "start_date": "2027-07-01",
                    "end_date": "2028-02-28",
                },
            ],
            "workforce_gaps": [
                {"role": "Cleanroom-certified HVAC Technician", "shortage": "4 techs for parallel ISO 5 + ISO 6 build"},
                {"role": "Orbital Welder (SS 316L, lab gas)", "shortage": "2 welders — critical path for lab gas installation"},
                {"role": "Commissioning Agent (Cx, LEED specialist)", "shortage": "1 additional CxA for parallel system testing"},
            ],
        },
    })


# ---------------------------------------------------------------------------
# Project 5: Regional Medical Center Expansion — Sacramento, CA
# ---------------------------------------------------------------------------


def _sacramento_hospital_fixture() -> dict[str, Any]:
    return _attach_building_definition({
        "projectSummary": {
            "project_name": "Sutter Health — Sacramento Medical Center, Patient Tower Expansion",
            "client_name": "Sutter Health (Owner) / HerreroBoldt (JV CM-at-Risk)",
            "location": "2825 Capitol Avenue, Sacramento, CA 95816",
            "project_type": "Healthcare — Acute Care Hospital Expansion",
            "budget": 712000000,
            "duration_months": 42,
            "scope": (
                "11-story, 460,000 GSF patient tower addition with 216 private patient rooms, "
                "32-bed ICU, 14 OR suites (including 2 hybrid OR), Level II trauma ED expansion, "
                "imaging suite (MRI, CT, PET/CT), central sterile processing, and rooftop "
                "helipad. OSHPD-3/SPC-4D seismic compliance. Connection to existing campus "
                "via 3rd-floor pedestrian bridge."
            ),
            "square_footage": 460000,
            "floor_count": 11,
            "complexity_level": "Critical",
            "start_date": "2025-03-01",
            "target_completion_date": "2028-09-01",
            "milestones": [
                {"name": "Notice to Proceed", "date": "2025-03-01"},
                {"name": "OSHPD Incremental Approval — Foundation", "date": "2025-06-15"},
                {"name": "Mat Foundation Pour", "date": "2025-12-15"},
                {"name": "Structural Topping Out", "date": "2027-01-31"},
                {"name": "Building Enclosure Complete", "date": "2027-07-31"},
                {"name": "OR Suite Fit-Out Complete", "date": "2028-04-30"},
                {"name": "OSHPD Final Inspection / CofO", "date": "2028-08-01"},
                {"name": "Patient Move-In", "date": "2028-09-01"},
            ],
        },
        "blueprintSummary": {
            "construction_type": "Type I-A (OSHPD-3, SPC-4D Seismic Performance Category)",
            "stories_above_grade": 11,
            "stories_below_grade": 1,
            "structural_steel_tons": 7400,
            "concrete_cy": 42000,
            "curtain_wall_sf": 95000,
            "lateral_system": "Buckling-restrained braced frames (BRBF) + steel moment frames",
            "foundation_type": "5 ft thick mat foundation with seismic base isolation (friction pendulum bearings)",
            "mep_highlights": {
                "operating_rooms": 14,
                "icu_beds": 32,
                "patient_rooms": 216,
                "imaging_suites": 6,
                "emergency_generators_kw": 6400,
                "medical_gas_zones": 8,
                "cooling_tons": 3600,
                "helipad": "FAA-approved, 62 ft diameter",
            },
        },
        "permitAssessment": {
            "required_permits": [
                {
                    "name": "OSHPD (HCAI) Plan Review & Incremental Approval",
                    "category": "State — CA Health Care Access & Information",
                    "status": "In Review",
                    "estimated_days": 45,
                },
                {
                    "name": "Sacramento City Building Permit",
                    "category": "Municipal — Community Development Dept",
                    "status": "Approved",
                    "estimated_days": 0,
                },
                {
                    "name": "Seismic Isolation System Special Approval (OSHPD IR)",
                    "category": "State — OSHPD Interpretation of Regulation",
                    "status": "Approved",
                    "estimated_days": 0,
                },
                {
                    "name": "SMAQMD Fugitive Dust & Diesel Emissions Permit",
                    "category": "Regional — Air Quality",
                    "status": "Approved",
                    "estimated_days": 0,
                },
                {
                    "name": "CA State Fire Marshal Plan Review (hospital occupancy)",
                    "category": "State — Fire/Life Safety",
                    "status": "In Review",
                    "estimated_days": 30,
                },
                {
                    "name": "FAA Helipad Airspace Determination",
                    "category": "Federal — FAA Form 7480-1",
                    "status": "Approved",
                    "estimated_days": 0,
                },
                {
                    "name": "Radiological Health Branch License (MRI/CT/PET)",
                    "category": "State — CA DPH RHB",
                    "status": "Pending",
                    "estimated_days": 60,
                },
            ]
        },
        "projectPlan": {
            "estimated_duration_days": 1279,
            "project_phases": [
                {
                    "name": "Site Preparation & Utilities Relocation",
                    "status": "completed",
                    "start_date": "2025-03-01",
                    "end_date": "2025-07-31",
                    "progress": 100,
                },
                {
                    "name": "Foundation & Base Isolation Installation",
                    "status": "completed",
                    "start_date": "2025-06-01",
                    "end_date": "2025-12-31",
                    "progress": 100,
                },
                {
                    "name": "Structural Steel & Concrete Decks",
                    "status": "in-progress",
                    "start_date": "2025-11-01",
                    "end_date": "2027-01-31",
                    "progress": 55,
                },
                {
                    "name": "Building Enclosure (curtain wall, roofing)",
                    "status": "in-progress",
                    "start_date": "2026-06-01",
                    "end_date": "2027-07-31",
                    "progress": 20,
                },
                {
                    "name": "MEP Rough-In (OSHPD-inspected installations)",
                    "status": "in-progress",
                    "start_date": "2026-04-01",
                    "end_date": "2027-10-31",
                    "progress": 15,
                },
                {
                    "name": "Interior Build-Out — Patient Floors (L3–L11)",
                    "status": "pending",
                    "start_date": "2027-02-01",
                    "end_date": "2028-03-31",
                    "progress": 0,
                },
                {
                    "name": "OR Suite & Imaging Fit-Out (L2)",
                    "status": "pending",
                    "start_date": "2027-06-01",
                    "end_date": "2028-04-30",
                    "progress": 0,
                },
                {
                    "name": "Helipad & Rooftop MEP",
                    "status": "pending",
                    "start_date": "2027-04-01",
                    "end_date": "2027-10-31",
                    "progress": 0,
                },
                {
                    "name": "Pedestrian Bridge Connection to Existing",
                    "status": "pending",
                    "start_date": "2027-08-01",
                    "end_date": "2028-01-31",
                    "progress": 0,
                },
                {
                    "name": "Commissioning, OSHPD Final & Patient Move",
                    "status": "pending",
                    "start_date": "2028-03-01",
                    "end_date": "2028-09-01",
                    "progress": 0,
                },
            ],
            "materials": [
                {"material_name": "Structural Steel (ASTM A992 W-shapes, BRBF cores)", "quantity": 7400, "unit": "TON"},
                {"material_name": "Concrete (5000 psi lightweight, composite deck)", "quantity": 42000, "unit": "CY"},
                {"material_name": "Friction Pendulum Bearings (EPS isolators)", "quantity": 68, "unit": "EA"},
                {"material_name": "Medical Gas Piping (ASTM B819 copper, brazed)", "quantity": 48000, "unit": "LF"},
                {"material_name": "Lead-Lined Drywall (1/16\" Pb, imaging suites)", "quantity": 18000, "unit": "SF"},
                {"material_name": "OR Modular Ceiling Systems (Brandon Medical)", "quantity": 14, "unit": "SET"},
                {"material_name": "Nurse Call System (Rauland Responder 5)", "quantity": 248, "unit": "STATION"},
                {"material_name": "Seismic Bracing (Hilti MQ-series, per OSHPD OPA)", "quantity": 6200, "unit": "EA"},
            ],
            "inspection_stages": [
                {"name": "Seismic isolator prototype test (ASCE 7 Ch17)", "phase": "Foundation", "status": "passed"},
                {"name": "BRBF frame connection welding inspection (AWS D1.8)", "phase": "Structure", "status": "in-progress"},
                {"name": "OSHPD in-progress inspection (IOR present, structural)", "phase": "Structure", "status": "in-progress"},
                {"name": "Medical gas purity verification (ASSE 6030)", "phase": "MEP", "status": "planned"},
                {"name": "OR laminar flow hood HEPA filter integrity (DOP test)", "phase": "OR Suite", "status": "planned"},
                {"name": "MRI 5-gauss line verification & RF shielding test", "phase": "Imaging", "status": "planned"},
                {"name": "Fire alarm & mass notification integration test", "phase": "Life Safety", "status": "planned"},
                {"name": "Emergency power system 4-hr load bank test", "phase": "Commissioning", "status": "planned"},
                {"name": "Helipad structural load test (FAA AC 150/5390-2D)", "phase": "Helipad", "status": "planned"},
            ],
            "dependencies": [
                {"predecessor": "Site Preparation & Utilities Relocation", "successor": "Foundation & Base Isolation Installation"},
                {"predecessor": "Foundation & Base Isolation Installation", "successor": "Structural Steel & Concrete Decks"},
                {"predecessor": "Structural Steel & Concrete Decks", "successor": "Building Enclosure (curtain wall, roofing)"},
                {"predecessor": "Structural Steel & Concrete Decks", "successor": "MEP Rough-In (OSHPD-inspected installations)"},
                {"predecessor": "Building Enclosure (curtain wall, roofing)", "successor": "Interior Build-Out — Patient Floors (L3–L11)"},
                {"predecessor": "MEP Rough-In (OSHPD-inspected installations)", "successor": "OR Suite & Imaging Fit-Out (L2)"},
                {"predecessor": "Structural Steel & Concrete Decks", "successor": "Helipad & Rooftop MEP"},
                {"predecessor": "Building Enclosure (curtain wall, roofing)", "successor": "Pedestrian Bridge Connection to Existing"},
                {"predecessor": "OR Suite & Imaging Fit-Out (L2)", "successor": "Commissioning, OSHPD Final & Patient Move"},
                {"predecessor": "Interior Build-Out — Patient Floors (L3–L11)", "successor": "Commissioning, OSHPD Final & Patient Move"},
            ],
        },
        "supplierAnalysis": {
            "procurement_plan": [
                {
                    "material_name": "Friction Pendulum Bearings (Earthquake Protection Systems)",
                    "supplier_name": "Earthquake Protection Systems Inc.",
                    "quantity": 68,
                    "unit_price": 125000.00,
                    "delivery_date": "2025-07-01",
                    "total_cost": 8500000.0,
                    "lead_time_weeks": 24,
                },
                {
                    "material_name": "Buckling-Restrained Braces (CoreBrace series)",
                    "supplier_name": "CoreBrace LLC",
                    "quantity": 96,
                    "unit_price": 42000.00,
                    "delivery_date": "2025-10-01",
                    "total_cost": 4032000.0,
                    "lead_time_weeks": 16,
                },
                {
                    "material_name": "MRI System — Siemens MAGNETOM Vida 3T",
                    "supplier_name": "Siemens Healthineers",
                    "quantity": 2,
                    "unit_price": 3200000.00,
                    "delivery_date": "2027-09-01",
                    "total_cost": 6400000.0,
                    "lead_time_weeks": 36,
                },
                {
                    "material_name": "OR Modular Ceiling System (Brandon Medical Megasuite)",
                    "supplier_name": "Brandon Medical Co. Ltd. (UK)",
                    "quantity": 14,
                    "unit_price": 180000.00,
                    "delivery_date": "2027-05-15",
                    "total_cost": 2520000.0,
                    "lead_time_weeks": 28,
                },
                {
                    "material_name": "Emergency Diesel Generators (MTU 16V4000 DS3000, 2MW)",
                    "supplier_name": "Rolls-Royce Power Systems / Peterson Power",
                    "quantity": 4,
                    "unit_price": 1200000.00,
                    "delivery_date": "2026-09-01",
                    "total_cost": 4800000.0,
                    "lead_time_weeks": 34,
                },
            ],
            "supply_chain_risks": [
                {
                    "risk": "OSHPD documentation & approval cycle delays (incremental reviews)",
                    "severity": "Critical",
                    "mitigation": "Dedicated OSHPD liaison on-site; weekly submittals; pre-approved alternates for long-lead items",
                },
                {
                    "risk": "Siemens MRI delivery slip due to helium supply shortage",
                    "severity": "High",
                    "mitigation": "Helium-free MAGNETOM Free.Max as backup; site ready for either unit",
                },
                {
                    "risk": "Seismic isolation bearing — single domestic manufacturer",
                    "severity": "Medium",
                    "mitigation": "Bearings on-site; spare units (2 extra) stored for construction-phase damage replacement",
                },
                {
                    "risk": "Lead-lined drywall supply limited to 3 domestic fabricators",
                    "severity": "Low",
                    "mitigation": "Order placed 10 months prior; MarShield as secondary source",
                },
            ],
        },
        "crewAnalysis": {
            "crew_allocations": [
                {
                    "phase_name": "Structural Steel & Concrete Decks",
                    "crew_name": "Herrick Corporation — Steel Erectors (Bill Frazier, Superintendent)",
                    "skill_type": "Ironworker (Local 118)",
                    "headcount": 42,
                    "labor_cost": 7140000.0,
                    "start_date": "2025-11-01",
                    "end_date": "2027-01-31",
                },
                {
                    "phase_name": "MEP Rough-In (OSHPD)",
                    "crew_name": "ACCO Engineered Systems (Kevin Tran, PM)",
                    "skill_type": "Sheet Metal Worker / Pipefitter (UA Local 447)",
                    "headcount": 65,
                    "labor_cost": 9750000.0,
                    "start_date": "2026-04-01",
                    "end_date": "2027-10-31",
                },
                {
                    "phase_name": "OR Suite & Imaging Fit-Out",
                    "crew_name": "Skanska — Healthcare Interiors (Dr. Lisa Okafor, QA Manager)",
                    "skill_type": "Medical Equipment Installer / Finish Carpenter",
                    "headcount": 30,
                    "labor_cost": 5400000.0,
                    "start_date": "2027-06-01",
                    "end_date": "2028-04-30",
                },
                {
                    "phase_name": "Building Enclosure",
                    "crew_name": "Walters & Wolf — Facade (Miguel Sandoval, Foreman)",
                    "skill_type": "Glazier (Local 169)",
                    "headcount": 22,
                    "labor_cost": 3300000.0,
                    "start_date": "2026-06-01",
                    "end_date": "2027-07-31",
                },
                {
                    "phase_name": "Commissioning",
                    "crew_name": "Affiliated Engineers — Cx Team (Karen Walsh, CxA)",
                    "skill_type": "Commissioning Agent (healthcare-certified)",
                    "headcount": 8,
                    "labor_cost": 1600000.0,
                    "start_date": "2028-03-01",
                    "end_date": "2028-09-01",
                },
            ],
            "workforce_gaps": [
                {"role": "OSHPD-certified Welder (AWS D1.1 + OSHPD special inspection)", "shortage": "6 welders for BRBF connection peak"},
                {"role": "Medical Gas Installer (ASSE 6010 certified)", "shortage": "3 installers — critical path for OR gas rough-in"},
                {"role": "MRI Installation Technician (Siemens-certified)", "shortage": "Pending vendor dispatch confirmation"},
            ],
        },
    })


# ---------------------------------------------------------------------------
# Fixture registry
# ---------------------------------------------------------------------------

DEMO_PROJECT_FIXTURES: list[dict[str, Any]] = [
    {"slug": "hudson-yards-tower", "pipeline": _hudson_tower_fixture()},
    {"slug": "ashburn-datacenter", "pipeline": _ashburn_datacenter_fixture()},
    {"slug": "oceana-miami", "pipeline": _miami_condo_fixture()},
    {"slug": "mit-science-complex", "pipeline": _boston_research_fixture()},
    {"slug": "sutter-health-sacramento", "pipeline": _sacramento_hospital_fixture()},
]


def fixture_pipeline_keys(pipeline: dict[str, Any]) -> list[str]:
    return sorted(pipeline.keys())


def fixture_to_json(pipeline: dict[str, Any]) -> str:
    return json.dumps(pipeline, default=str)
