"""Comprehensive master data fixtures for suppliers, materials, and crew.

This module provides expanded master data catalogs with 20 suppliers (200+ materials)
and 50+ crew members across diverse construction specialties.
"""

from decimal import Decimal


# ==============================================================================
# SUPPLIER MASTER DATA (20 suppliers with 200+ materials)
# ==============================================================================

SUPPLIER_MASTER_DATA: list[dict] = [
    # ===== STRUCTURAL STEEL SUPPLIERS (3) =====
    {
        "supplier_code": "SUP-USS-01",
        "supplier_name": "United Structural Steel Corp",
        "supplier_category": "Structural Steel",
        "contact_person": "Michael Rodriguez",
        "email": "m.rodriguez@unitedsteel.example",
        "phone": "+1-412-555-8100",
        "location": "Pittsburgh, PA",
        "lead_time_days": 120,
        "reliability_score": Decimal("89.50"),
        "preferred_supplier": True,
        "status": "active",
        "materials": [
            {
                "material_name": "Wide Flange Beam W24x131",
                "material_category": "Structural Steel",
                "unit_price": Decimal("4250.00"),
                "currency_code": "USD",
                "moq": 8,
                "lead_time_days": 120,
            },
            {
                "material_name": "Wide Flange Column W14x500",
                "material_category": "Structural Steel",
                "unit_price": Decimal("5800.00"),
                "currency_code": "USD",
                "moq": 4,
                "lead_time_days": 140,
            },
            {
                "material_name": "HSS 12x12x1/2 Square Hollow Section",
                "material_category": "Structural Steel",
                "unit_price": Decimal("4100.00"),
                "currency_code": "USD",
                "moq": 6,
                "lead_time_days": 90,
            },
            {
                "material_name": "Steel Plate 3/4 inch A992",
                "material_category": "Structural Steel",
                "unit_price": Decimal("1.45"),
                "currency_code": "USD",
                "moq": 3000,
                "lead_time_days": 45,
            },
            {
                "material_name": "Angle Section L8x8x1",
                "material_category": "Structural Steel",
                "unit_price": Decimal("2.15"),
                "currency_code": "USD",
                "moq": 1000,
                "lead_time_days": 60,
            },
            {
                "material_name": "Composite Metal Deck 2-inch (18 gauge)",
                "material_category": "Floor Systems",
                "unit_price": Decimal("0.92"),
                "currency_code": "USD",
                "moq": 15000,
                "lead_time_days": 35,
            },
            {
                "material_name": "Rebar #6 Grade 80 (High Strength)",
                "material_category": "Reinforcement",
                "unit_price": Decimal("1.28"),
                "currency_code": "USD",
                "moq": 4000,
                "lead_time_days": 30,
            },
            {
                "material_name": "Structural Bolts ASTM A325 3/4 inch",
                "material_category": "Connections",
                "unit_price": Decimal("0.85"),
                "currency_code": "USD",
                "moq": 10000,
                "lead_time_days": 21,
            },
            {
                "material_name": "Welded Wire Mesh W4xW4-D4xD4",
                "material_category": "Reinforcement",
                "unit_price": Decimal("1.65"),
                "currency_code": "USD",
                "moq": 5000,
                "lead_time_days": 28,
            },
            {
                "material_name": "Steel Beam W36x210 (Long Span)",
                "material_category": "Structural Steel",
                "unit_price": Decimal("6200.00"),
                "currency_code": "USD",
                "moq": 5,
                "lead_time_days": 150,
            },
        ],
    },
    {
        "supplier_code": "SUP-NBC-02",
        "supplier_name": "Nucor Building Components",
        "supplier_category": "Structural Steel",
        "contact_person": "Jennifer Liu",
        "email": "j.liu@nucorbuild.example",
        "phone": "+1-704-555-9200",
        "location": "Charlotte, NC",
        "lead_time_days": 95,
        "reliability_score": Decimal("92.00"),
        "preferred_supplier": True,
        "status": "active",
        "materials": [
            {
                "material_name": "Wide Flange Beam W18x86",
                "material_category": "Structural Steel",
                "unit_price": Decimal("3100.00"),
                "currency_code": "USD",
                "moq": 10,
                "lead_time_days": 95,
            },
            {
                "material_name": "Wide Flange Column W12x336",
                "material_category": "Structural Steel",
                "unit_price": Decimal("4850.00"),
                "currency_code": "USD",
                "moq": 6,
                "lead_time_days": 110,
            },
            {
                "material_name": "HSS 10x10x5/8 Square Hollow Section",
                "material_category": "Structural Steel",
                "unit_price": Decimal("3650.00"),
                "currency_code": "USD",
                "moq": 8,
                "lead_time_days": 80,
            },
            {
                "material_name": "Rebar #9 Grade 75",
                "material_category": "Reinforcement",
                "unit_price": Decimal("1.55"),
                "currency_code": "USD",
                "moq": 2500,
                "lead_time_days": 35,
            },
            {
                "material_name": "Steel Joist K-Series 24K9",
                "material_category": "Roof/Floor Systems",
                "unit_price": Decimal("285.00"),
                "currency_code": "USD",
                "moq": 50,
                "lead_time_days": 70,
            },
            {
                "material_name": "Roof Deck 1.5-inch (22 gauge)",
                "material_category": "Roof Systems",
                "unit_price": Decimal("0.68"),
                "currency_code": "USD",
                "moq": 12000,
                "lead_time_days": 42,
            },
            {
                "material_name": "Stud Anchors 5/8 inch x 6 inch",
                "material_category": "Connections",
                "unit_price": Decimal("1.15"),
                "currency_code": "USD",
                "moq": 8000,
                "lead_time_days": 25,
            },
            {
                "material_name": "Steel Channel C12x30",
                "material_category": "Structural Steel",
                "unit_price": Decimal("2280.00"),
                "currency_code": "USD",
                "moq": 12,
                "lead_time_days": 85,
            },
            {
                "material_name": "Expansion Joints Heavy Duty 4-inch",
                "material_category": "Specialty Items",
                "unit_price": Decimal("185.00"),
                "currency_code": "USD",
                "moq": 100,
                "lead_time_days": 50,
            },
            {
                "material_name": "Post-Tensioning Tendons 15.2mm 7-wire",
                "material_category": "Prestressed Systems",
                "unit_price": Decimal("3.85"),
                "currency_code": "USD",
                "moq": 20000,
                "lead_time_days": 90,
            },
        ],
    },
    {
        "supplier_code": "SUP-CSI-03",
        "supplier_name": "Commercial Steel Industries",
        "supplier_category": "Structural Steel",
        "contact_person": "David Park",
        "email": "d.park@comsteel.example",
        "phone": "+1-713-555-3400",
        "location": "Houston, TX",
        "lead_time_days": 105,
        "reliability_score": Decimal("85.50"),
        "preferred_supplier": False,
        "status": "active",
        "materials": [
            {
                "material_name": "Wide Flange Beam W30x173",
                "material_category": "Structural Steel",
                "unit_price": Decimal("5100.00"),
                "currency_code": "USD",
                "moq": 6,
                "lead_time_days": 105,
            },
            {
                "material_name": "HSS 8x8x1/2 Round Hollow Section",
                "material_category": "Structural Steel",
                "unit_price": Decimal("3200.00"),
                "currency_code": "USD",
                "moq": 10,
                "lead_time_days": 85,
            },
            {
                "material_name": "Rebar #10 Grade 60",
                "material_category": "Reinforcement",
                "unit_price": Decimal("1.75"),
                "currency_code": "USD",
                "moq": 2000,
                "lead_time_days": 40,
            },
            {
                "material_name": "Steel Trusses 60-ft Span Bowstring",
                "material_category": "Long Span Systems",
                "unit_price": Decimal("12500.00"),
                "currency_code": "USD",
                "moq": 2,
                "lead_time_days": 120,
            },
            {
                "material_name": "Shear Studs 3/4 inch x 4 inch",
                "material_category": "Connections",
                "unit_price": Decimal("0.95"),
                "currency_code": "USD",
                "moq": 12000,
                "lead_time_days": 30,
            },
            {
                "material_name": "Girder Plates 2 inch A572 Grade 50",
                "material_category": "Structural Steel",
                "unit_price": Decimal("2.35"),
                "currency_code": "USD",
                "moq": 2000,
                "lead_time_days": 60,
            },
            {
                "material_name": "Cable Tray Support Steel 12-inch",
                "material_category": "MEP Support",
                "unit_price": Decimal("48.00"),
                "currency_code": "USD",
                "moq": 200,
                "lead_time_days": 45,
            },
            {
                "material_name": "Seismic Bracing Rods 1-inch Diameter",
                "material_category": "Seismic Systems",
                "unit_price": Decimal("15.50"),
                "currency_code": "USD",
                "moq": 500,
                "lead_time_days": 35,
            },
            {
                "material_name": "Embed Plates 12x12x1 inch with Anchors",
                "material_category": "Connections",
                "unit_price": Decimal("85.00"),
                "currency_code": "USD",
                "moq": 100,
                "lead_time_days": 40,
            },
            {
                "material_name": "Handrail System Stainless 42-inch Height",
                "material_category": "Architectural Steel",
                "unit_price": Decimal("125.00"),
                "currency_code": "USD",
                "moq": 300,
                "lead_time_days": 55,
            },
        ],
    },

    # ===== CONCRETE & AGGREGATE SUPPLIERS (2) =====
    {
        "supplier_code": "SUP-HCC-04",
        "supplier_name": "Holcim Concrete Co",
        "supplier_category": "Concrete & Aggregates",
        "contact_person": "Maria Gonzalez",
        "email": "m.gonzalez@holcim.example",
        "phone": "+1-415-555-7200",
        "location": "San Francisco, CA",
        "lead_time_days": 14,
        "reliability_score": Decimal("94.00"),
        "preferred_supplier": True,
        "status": "active",
        "materials": [
            {
                "material_name": "Ready-Mix Concrete 4000 PSI",
                "material_category": "Concrete",
                "unit_price": Decimal("145.00"),
                "currency_code": "USD",
                "moq": 10,
                "lead_time_days": 7,
            },
            {
                "material_name": "Ready-Mix Concrete 5000 PSI High Strength",
                "material_category": "Concrete",
                "unit_price": Decimal("165.00"),
                "currency_code": "USD",
                "moq": 10,
                "lead_time_days": 7,
            },
            {
                "material_name": "Ready-Mix Concrete 8000 PSI Superplasticizer",
                "material_category": "Specialty Concrete",
                "unit_price": Decimal("245.00"),
                "currency_code": "USD",
                "moq": 15,
                "lead_time_days": 14,
            },
            {
                "material_name": "Shotcrete 4500 PSI Fiber Reinforced",
                "material_category": "Specialty Concrete",
                "unit_price": Decimal("185.00"),
                "currency_code": "USD",
                "moq": 8,
                "lead_time_days": 10,
            },
            {
                "material_name": "Self-Consolidating Concrete 6000 PSI",
                "material_category": "Specialty Concrete",
                "unit_price": Decimal("210.00"),
                "currency_code": "USD",
                "moq": 12,
                "lead_time_days": 10,
            },
            {
                "material_name": "Lightweight Concrete 3500 PSI",
                "material_category": "Concrete",
                "unit_price": Decimal("175.00"),
                "currency_code": "USD",
                "moq": 10,
                "lead_time_days": 14,
            },
            {
                "material_name": "Grout High Strength Non-Shrink",
                "material_category": "Specialty Concrete",
                "unit_price": Decimal("42.00"),
                "currency_code": "USD",
                "moq": 200,
                "lead_time_days": 5,
            },
            {
                "material_name": "Aggregate 3/4 inch Crushed Stone",
                "material_category": "Aggregates",
                "unit_price": Decimal("35.00"),
                "currency_code": "USD",
                "moq": 50,
                "lead_time_days": 3,
            },
            {
                "material_name": "Sand Concrete Grade Washed",
                "material_category": "Aggregates",
                "unit_price": Decimal("32.00"),
                "currency_code": "USD",
                "moq": 50,
                "lead_time_days": 3,
            },
            {
                "material_name": "Flyash Type C Pozzolan",
                "material_category": "Admixtures",
                "unit_price": Decimal("85.00"),
                "currency_code": "USD",
                "moq": 100,
                "lead_time_days": 14,
            },
            {
                "material_name": "Silica Fume Densified",
                "material_category": "Admixtures",
                "unit_price": Decimal("125.00"),
                "currency_code": "USD",
                "moq": 50,
                "lead_time_days": 21,
            },
        ],
    },
    {
        "supplier_code": "SUP-CMS-05",
        "supplier_name": "CementMaster Supplies",
        "supplier_category": "Concrete & Aggregates",
        "contact_person": "Robert Chen",
        "email": "r.chen@cementmaster.example",
        "phone": "+1-303-555-6100",
        "location": "Denver, CO",
        "lead_time_days": 10,
        "reliability_score": Decimal("88.50"),
        "preferred_supplier": False,
        "status": "active",
        "materials": [
            {
                "material_name": "Portland Cement Type I/II Bulk",
                "material_category": "Cement",
                "unit_price": Decimal("115.00"),
                "currency_code": "USD",
                "moq": 40,
                "lead_time_days": 10,
            },
            {
                "material_name": "Portland Cement Type III High Early",
                "material_category": "Cement",
                "unit_price": Decimal("135.00"),
                "currency_code": "USD",
                "moq": 40,
                "lead_time_days": 14,
            },
            {
                "material_name": "Masonry Cement Type N",
                "material_category": "Cement",
                "unit_price": Decimal("18.50"),
                "currency_code": "USD",
                "moq": 500,
                "lead_time_days": 7,
            },
            {
                "material_name": "Precast Concrete Hollow Core Slabs 8-inch",
                "material_category": "Precast",
                "unit_price": Decimal("45.00"),
                "currency_code": "USD",
                "moq": 500,
                "lead_time_days": 45,
            },
            {
                "material_name": "Precast Concrete Beams 24-inch Depth",
                "material_category": "Precast",
                "unit_price": Decimal("285.00"),
                "currency_code": "USD",
                "moq": 20,
                "lead_time_days": 60,
            },
            {
                "material_name": "Concrete Blocks CMU 8x8x16",
                "material_category": "Masonry",
                "unit_price": Decimal("3.85"),
                "currency_code": "USD",
                "moq": 2000,
                "lead_time_days": 14,
            },
            {
                "material_name": "Mortar Mix Type S Bagged",
                "material_category": "Masonry",
                "unit_price": Decimal("12.50"),
                "currency_code": "USD",
                "moq": 300,
                "lead_time_days": 7,
            },
            {
                "material_name": "Waterproofing Membrane Cementitious",
                "material_category": "Waterproofing",
                "unit_price": Decimal("8.50"),
                "currency_code": "USD",
                "moq": 1000,
                "lead_time_days": 21,
            },
            {
                "material_name": "Epoxy Floor Coating High Traffic",
                "material_category": "Coatings",
                "unit_price": Decimal("6.25"),
                "currency_code": "USD",
                "moq": 500,
                "lead_time_days": 28,
            },
            {
                "material_name": "Concrete Repair Mortar Rapid Set",
                "material_category": "Specialty Materials",
                "unit_price": Decimal("38.00"),
                "currency_code": "USD",
                "moq": 200,
                "lead_time_days": 14,
            },
        ],
    },

    # ===== CURTAIN WALL & GLAZING SUPPLIERS (2) =====
    {
        "supplier_code": "SUP-YKK-06",
        "supplier_name": "YKK AP Facade Systems",
        "supplier_category": "Curtain Wall & Glass",
        "contact_person": "Kenji Tanaka",
        "email": "k.tanaka@ykk-facade.example",
        "phone": "+1-770-555-2200",
        "location": "Atlanta, GA",
        "lead_time_days": 180,
        "reliability_score": Decimal("96.00"),
        "preferred_supplier": True,
        "status": "active",
        "materials": [
            {
                "material_name": "Unitized Curtain Wall System 4-Side SSG",
                "material_category": "Curtain Wall",
                "unit_price": Decimal("185.00"),
                "currency_code": "USD",
                "moq": 5000,
                "lead_time_days": 180,
            },
            {
                "material_name": "Stick-Built Curtain Wall Mullions 6-inch",
                "material_category": "Curtain Wall",
                "unit_price": Decimal("95.00"),
                "currency_code": "USD",
                "moq": 1000,
                "lead_time_days": 160,
            },
            {
                "material_name": "Triple-Glazed IGU Low-E 1-inch x 1/2-inch x 1-inch",
                "material_category": "Glazing",
                "unit_price": Decimal("65.00"),
                "currency_code": "USD",
                "moq": 2000,
                "lead_time_days": 90,
            },
            {
                "material_name": "Spandrel Glass Ceramic Frit Back-Painted",
                "material_category": "Glazing",
                "unit_price": Decimal("48.00"),
                "currency_code": "USD",
                "moq": 1500,
                "lead_time_days": 100,
            },
            {
                "material_name": "Structural Silicone Sealant Dow Corning 995",
                "material_category": "Sealants",
                "unit_price": Decimal("28.00"),
                "currency_code": "USD",
                "moq": 200,
                "lead_time_days": 30,
            },
            {
                "material_name": "Aluminum Extrusions 6063-T6 Custom Profiles",
                "material_category": "Framing",
                "unit_price": Decimal("12.50"),
                "currency_code": "USD",
                "moq": 5000,
                "lead_time_days": 120,
            },
            {
                "material_name": "Operable Windows Casement 4x6 ft",
                "material_category": "Windows",
                "unit_price": Decimal("850.00"),
                "currency_code": "USD",
                "moq": 50,
                "lead_time_days": 140,
            },
            {
                "material_name": "Vision Glass Low Iron Extra Clear 10mm",
                "material_category": "Glazing",
                "unit_price": Decimal("38.00"),
                "currency_code": "USD",
                "moq": 3000,
                "lead_time_days": 75,
            },
            {
                "material_name": "Thermal Breaks Polyamide 24mm",
                "material_category": "Insulation Components",
                "unit_price": Decimal("5.50"),
                "currency_code": "USD",
                "moq": 2000,
                "lead_time_days": 90,
            },
            {
                "material_name": "Pressure Plates Aluminum Anodized",
                "material_category": "Accessories",
                "unit_price": Decimal("18.00"),
                "currency_code": "USD",
                "moq": 1000,
                "lead_time_days": 60,
            },
        ],
    },
    {
        "supplier_code": "SUP-VIT-07",
        "supplier_name": "Vitro Architectural Glass",
        "supplier_category": "Curtain Wall & Glass",
        "contact_person": "Isabella Martinez",
        "email": "i.martinez@vitroglass.example",
        "phone": "+1-412-555-4400",
        "location": "Pittsburgh, PA",
        "lead_time_days": 95,
        "reliability_score": Decimal("91.50"),
        "preferred_supplier": False,
        "status": "active",
        "materials": [
            {
                "material_name": "Double-Glazed IGU Argon-Filled 1-inch",
                "material_category": "Glazing",
                "unit_price": Decimal("42.00"),
                "currency_code": "USD",
                "moq": 2500,
                "lead_time_days": 70,
            },
            {
                "material_name": "Laminated Safety Glass 1/2-inch PVB Interlayer",
                "material_category": "Glazing",
                "unit_price": Decimal("52.00"),
                "currency_code": "USD",
                "moq": 1800,
                "lead_time_days": 85,
            },
            {
                "material_name": "Tempered Glass 3/8-inch Heat Strengthened",
                "material_category": "Glazing",
                "unit_price": Decimal("28.00"),
                "currency_code": "USD",
                "moq": 3000,
                "lead_time_days": 60,
            },
            {
                "material_name": "Electrochromic Smart Glass Tintable",
                "material_category": "Specialty Glass",
                "unit_price": Decimal("285.00"),
                "currency_code": "USD",
                "moq": 200,
                "lead_time_days": 150,
            },
            {
                "material_name": "Point-Supported Glass Fittings Stainless",
                "material_category": "Hardware",
                "unit_price": Decimal("125.00"),
                "currency_code": "USD",
                "moq": 100,
                "lead_time_days": 75,
            },
            {
                "material_name": "Insulated Glass Spacer Bars Warm Edge",
                "material_category": "IGU Components",
                "unit_price": Decimal("3.50"),
                "currency_code": "USD",
                "moq": 5000,
                "lead_time_days": 40,
            },
            {
                "material_name": "Weatherseal EPDM Gaskets",
                "material_category": "Sealants",
                "unit_price": Decimal("4.85"),
                "currency_code": "USD",
                "moq": 2000,
                "lead_time_days": 35,
            },
            {
                "material_name": "Entrance Door System Aluminum Frameless",
                "material_category": "Doors",
                "unit_price": Decimal("2850.00"),
                "currency_code": "USD",
                "moq": 10,
                "lead_time_days": 120,
            },
            {
                "material_name": "Glass Canopy System Cable-Supported",
                "material_category": "Specialty Systems",
                "unit_price": Decimal("450.00"),
                "currency_code": "USD",
                "moq": 100,
                "lead_time_days": 140,
            },
            {
                "material_name": "Skylight System Pyramidal Aluminum Frame",
                "material_category": "Specialty Systems",
                "unit_price": Decimal("385.00"),
                "currency_code": "USD",
                "moq": 50,
                "lead_time_days": 130,
            },
        ],
    },

    # ===== MEP EQUIPMENT SUPPLIERS (3) =====
    {
        "supplier_code": "SUP-TRN-08",
        "supplier_name": "Trane Commercial HVAC",
        "supplier_category": "MEP Equipment - HVAC",
        "contact_person": "Thomas Wright",
        "email": "t.wright@trane.example",
        "phone": "+1-608-555-1800",
        "location": "La Crosse, WI",
        "lead_time_days": 120,
        "reliability_score": Decimal("93.50"),
        "preferred_supplier": True,
        "status": "active",
        "materials": [
            {
                "material_name": "Chiller Air-Cooled 500 Ton Centrifugal",
                "material_category": "HVAC - Chillers",
                "unit_price": Decimal("285000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 150,
            },
            {
                "material_name": "Chiller Water-Cooled 1000 Ton Magnetic Bearing",
                "material_category": "HVAC - Chillers",
                "unit_price": Decimal("485000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 180,
            },
            {
                "material_name": "Rooftop Unit Package 50 Ton DX",
                "material_category": "HVAC - RTUs",
                "unit_price": Decimal("38500.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 90,
            },
            {
                "material_name": "Air Handling Unit (AHU) 25,000 CFM Variable Speed",
                "material_category": "HVAC - AHUs",
                "unit_price": Decimal("52000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 120,
            },
            {
                "material_name": "Variable Refrigerant Flow (VRF) System 60HP",
                "material_category": "HVAC - VRF",
                "unit_price": Decimal("125000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 110,
            },
            {
                "material_name": "Fan Coil Unit 4-Pipe 800 CFM",
                "material_category": "HVAC - Terminal Units",
                "unit_price": Decimal("1850.00"),
                "currency_code": "USD",
                "moq": 10,
                "lead_time_days": 70,
            },
            {
                "material_name": "Energy Recovery Ventilator (ERV) 10,000 CFM",
                "material_category": "HVAC - Ventilation",
                "unit_price": Decimal("28500.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 100,
            },
            {
                "material_name": "Cooling Tower Open Circuit 800 Ton",
                "material_category": "HVAC - Cooling Towers",
                "unit_price": Decimal("95000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 140,
            },
            {
                "material_name": "Boiler Gas-Fired Condensing 2000 MBH",
                "material_category": "HVAC - Boilers",
                "unit_price": Decimal("45000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 130,
            },
            {
                "material_name": "VAV Box Pressure Independent 2000 CFM",
                "material_category": "HVAC - Terminal Units",
                "unit_price": Decimal("2450.00"),
                "currency_code": "USD",
                "moq": 15,
                "lead_time_days": 60,
            },
        ],
    },
    {
        "supplier_code": "SUP-EAT-09",
        "supplier_name": "Eaton Electrical Systems",
        "supplier_category": "MEP Equipment - Electrical",
        "contact_person": "Patricia Johnson",
        "email": "p.johnson@eaton.example",
        "phone": "+1-216-555-3300",
        "location": "Cleveland, OH",
        "lead_time_days": 85,
        "reliability_score": Decimal("90.00"),
        "preferred_supplier": True,
        "status": "active",
        "materials": [
            {
                "material_name": "Main Distribution Panel 4000A 480V",
                "material_category": "Electrical - Panels",
                "unit_price": Decimal("125000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 120,
            },
            {
                "material_name": "Switchgear Medium Voltage 15kV 2000A",
                "material_category": "Electrical - Switchgear",
                "unit_price": Decimal("285000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 150,
            },
            {
                "material_name": "Generator Diesel 2000kW Prime Power",
                "material_category": "Electrical - Generators",
                "unit_price": Decimal("485000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 140,
            },
            {
                "material_name": "UPS System 500kVA Double Conversion",
                "material_category": "Electrical - UPS",
                "unit_price": Decimal("185000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 100,
            },
            {
                "material_name": "Transformer Dry Type 2500kVA 480-208V",
                "material_category": "Electrical - Transformers",
                "unit_price": Decimal("65000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 90,
            },
            {
                "material_name": "Circuit Breaker Molded Case 3-Pole 600A",
                "material_category": "Electrical - Protection",
                "unit_price": Decimal("1850.00"),
                "currency_code": "USD",
                "moq": 10,
                "lead_time_days": 45,
            },
            {
                "material_name": "Bus Duct 3000A Feeder Copper",
                "material_category": "Electrical - Distribution",
                "unit_price": Decimal("285.00"),
                "currency_code": "USD",
                "moq": 100,
                "lead_time_days": 75,
            },
            {
                "material_name": "Panelboard 225A MLO 42-Circuit 208V",
                "material_category": "Electrical - Panels",
                "unit_price": Decimal("2850.00"),
                "currency_code": "USD",
                "moq": 5,
                "lead_time_days": 60,
            },
            {
                "material_name": "Cable Tray Ladder Type 24-inch Aluminum",
                "material_category": "Electrical - Raceways",
                "unit_price": Decimal("48.00"),
                "currency_code": "USD",
                "moq": 500,
                "lead_time_days": 50,
            },
            {
                "material_name": "LED High Bay Fixture 200W 25,000 Lumens",
                "material_category": "Electrical - Lighting",
                "unit_price": Decimal("285.00"),
                "currency_code": "USD",
                "moq": 100,
                "lead_time_days": 40,
            },
        ],
    },
    {
        "supplier_code": "SUP-GRO-10",
        "supplier_name": "Grohe Plumbing Systems",
        "supplier_category": "MEP Equipment - Plumbing",
        "contact_person": "Klaus Schmidt",
        "email": "k.schmidt@grohe.example",
        "phone": "+1-630-555-2900",
        "location": "Oak Brook, IL",
        "lead_time_days": 75,
        "reliability_score": Decimal("87.50"),
        "preferred_supplier": False,
        "status": "active",
        "materials": [
            {
                "material_name": "Domestic Water Booster Pump 150 GPM",
                "material_category": "Plumbing - Pumps",
                "unit_price": Decimal("18500.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 90,
            },
            {
                "material_name": "Fire Pump Electric 1500 GPM UL Listed",
                "material_category": "Fire Protection",
                "unit_price": Decimal("85000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 120,
            },
            {
                "material_name": "Water Heater Gas Tankless Commercial 500k BTU",
                "material_category": "Plumbing - Water Heating",
                "unit_price": Decimal("8500.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 60,
            },
            {
                "material_name": "Backflow Preventer RPZ 6-inch",
                "material_category": "Plumbing - Protection",
                "unit_price": Decimal("4850.00"),
                "currency_code": "USD",
                "moq": 2,
                "lead_time_days": 50,
            },
            {
                "material_name": "Grease Interceptor 1000 Gallon",
                "material_category": "Plumbing - Drainage",
                "unit_price": Decimal("12500.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 70,
            },
            {
                "material_name": "Floor Drain Heavy Duty 12x12 inch",
                "material_category": "Plumbing - Drainage",
                "unit_price": Decimal("285.00"),
                "currency_code": "USD",
                "moq": 50,
                "lead_time_days": 35,
            },
            {
                "material_name": "Fixture Carrier Commercial Toilet Wall-Hung",
                "material_category": "Plumbing - Fixtures",
                "unit_price": Decimal("485.00"),
                "currency_code": "USD",
                "moq": 25,
                "lead_time_days": 45,
            },
            {
                "material_name": "Mixing Valve Thermostatic Anti-Scald",
                "material_category": "Plumbing - Controls",
                "unit_price": Decimal("185.00"),
                "currency_code": "USD",
                "moq": 40,
                "lead_time_days": 40,
            },
            {
                "material_name": "Eyewash Station Emergency Pedestal Mount",
                "material_category": "Plumbing - Safety",
                "unit_price": Decimal("1250.00"),
                "currency_code": "USD",
                "moq": 10,
                "lead_time_days": 50,
            },
            {
                "material_name": "Piping Insulation Fiberglass 3-inch",
                "material_category": "Plumbing - Insulation",
                "unit_price": Decimal("8.50"),
                "currency_code": "USD",
                "moq": 1000,
                "lead_time_days": 30,
            },
        ],
    },

    # ===== FINISHING MATERIALS SUPPLIERS (2) =====
    {
        "supplier_code": "SUP-GYP-11",
        "supplier_name": "USG Gypsum & Finishes",
        "supplier_category": "Interior Finishes",
        "contact_person": "Amanda Foster",
        "email": "a.foster@usg.example",
        "phone": "+1-312-555-7700",
        "location": "Chicago, IL",
        "lead_time_days": 21,
        "reliability_score": Decimal("91.00"),
        "preferred_supplier": True,
        "status": "active",
        "materials": [
            {
                "material_name": "Gypsum Board 5/8-inch Type X Fire-Rated",
                "material_category": "Drywall",
                "unit_price": Decimal("12.50"),
                "currency_code": "USD",
                "moq": 500,
                "lead_time_days": 14,
            },
            {
                "material_name": "Gypsum Board 1/2-inch Moisture Resistant",
                "material_category": "Drywall",
                "unit_price": Decimal("10.85"),
                "currency_code": "USD",
                "moq": 500,
                "lead_time_days": 14,
            },
            {
                "material_name": "Metal Studs 6-inch 20 Gauge",
                "material_category": "Framing",
                "unit_price": Decimal("4.25"),
                "currency_code": "USD",
                "moq": 1000,
                "lead_time_days": 21,
            },
            {
                "material_name": "Suspended Ceiling Grid 15/16-inch White",
                "material_category": "Ceilings",
                "unit_price": Decimal("2.85"),
                "currency_code": "USD",
                "moq": 2000,
                "lead_time_days": 28,
            },
            {
                "material_name": "Acoustic Ceiling Tiles 2x2 ft NRC 0.70",
                "material_category": "Ceilings",
                "unit_price": Decimal("4.50"),
                "currency_code": "USD",
                "moq": 1000,
                "lead_time_days": 21,
            },
            {
                "material_name": "Joint Compound All-Purpose 5-Gallon",
                "material_category": "Finishing",
                "unit_price": Decimal("28.00"),
                "currency_code": "USD",
                "moq": 100,
                "lead_time_days": 7,
            },
            {
                "material_name": "Corner Bead Metal 10 ft",
                "material_category": "Trim",
                "unit_price": Decimal("3.50"),
                "currency_code": "USD",
                "moq": 500,
                "lead_time_days": 14,
            },
            {
                "material_name": "Fiberglass Insulation Batt R-19 6.25-inch",
                "material_category": "Insulation",
                "unit_price": Decimal("0.85"),
                "currency_code": "USD",
                "moq": 5000,
                "lead_time_days": 21,
            },
            {
                "material_name": "Access Panel Fire-Rated 24x36 inch",
                "material_category": "Specialty Items",
                "unit_price": Decimal("185.00"),
                "currency_code": "USD",
                "moq": 25,
                "lead_time_days": 35,
            },
            {
                "material_name": "Shaft Wall Liner Panel 1-inch",
                "material_category": "Fire Barriers",
                "unit_price": Decimal("18.50"),
                "currency_code": "USD",
                "moq": 300,
                "lead_time_days": 28,
            },
        ],
    },
    {
        "supplier_code": "SUP-ARM-12",
        "supplier_name": "Armstrong Flooring Co",
        "supplier_category": "Flooring & Finishes",
        "contact_person": "Daniel Kim",
        "email": "d.kim@armstrong.example",
        "phone": "+1-717-555-8800",
        "location": "Lancaster, PA",
        "lead_time_days": 42,
        "reliability_score": Decimal("88.00"),
        "preferred_supplier": False,
        "status": "active",
        "materials": [
            {
                "material_name": "VCT Vinyl Composition Tile 12x12 Commercial",
                "material_category": "Flooring",
                "unit_price": Decimal("2.85"),
                "currency_code": "USD",
                "moq": 3000,
                "lead_time_days": 35,
            },
            {
                "material_name": "LVT Luxury Vinyl Tile Wood Look",
                "material_category": "Flooring",
                "unit_price": Decimal("5.50"),
                "currency_code": "USD",
                "moq": 2000,
                "lead_time_days": 42,
            },
            {
                "material_name": "Carpet Tile Modular 24x24 High Traffic",
                "material_category": "Flooring",
                "unit_price": Decimal("8.25"),
                "currency_code": "USD",
                "moq": 1500,
                "lead_time_days": 50,
            },
            {
                "material_name": "Rubber Flooring Athletic 3/8-inch",
                "material_category": "Specialty Flooring",
                "unit_price": Decimal("12.50"),
                "currency_code": "USD",
                "moq": 1000,
                "lead_time_days": 55,
            },
            {
                "material_name": "Epoxy Terrazzo Flooring System",
                "material_category": "Specialty Flooring",
                "unit_price": Decimal("35.00"),
                "currency_code": "USD",
                "moq": 500,
                "lead_time_days": 60,
            },
            {
                "material_name": "Ceramic Tile Porcelain 12x24 Rectified",
                "material_category": "Tile",
                "unit_price": Decimal("6.85"),
                "currency_code": "USD",
                "moq": 1000,
                "lead_time_days": 45,
            },
            {
                "material_name": "Base Molding Rubber 4-inch Cove",
                "material_category": "Trim",
                "unit_price": Decimal("2.50"),
                "currency_code": "USD",
                "moq": 2000,
                "lead_time_days": 28,
            },
            {
                "material_name": "Floor Leveler Self-Leveling Compound",
                "material_category": "Substrate",
                "unit_price": Decimal("42.00"),
                "currency_code": "USD",
                "moq": 200,
                "lead_time_days": 21,
            },
            {
                "material_name": "Waterproofing Membrane Sheet 60 mil",
                "material_category": "Waterproofing",
                "unit_price": Decimal("4.25"),
                "currency_code": "USD",
                "moq": 2000,
                "lead_time_days": 35,
            },
            {
                "material_name": "Hardwood Flooring Oak Engineered 5-inch",
                "material_category": "Flooring",
                "unit_price": Decimal("18.50"),
                "currency_code": "USD",
                "moq": 1000,
                "lead_time_days": 50,
            },
        ],
    },

    # ===== SITE & EARTHWORK SUPPLIERS (2) =====
    {
        "supplier_code": "SUP-CAT-13",
        "supplier_name": "Caterpillar Equipment Rental",
        "supplier_category": "Equipment & Site Work",
        "contact_person": "Frank Morrison",
        "email": "f.morrison@cat.example",
        "phone": "+1-309-555-4100",
        "location": "Peoria, IL",
        "lead_time_days": 14,
        "reliability_score": Decimal("90.50"),
        "preferred_supplier": True,
        "status": "active",
        "materials": [
            {
                "material_name": "Excavator 320 Size 48,000 lb (Monthly Rental)",
                "material_category": "Heavy Equipment",
                "unit_price": Decimal("12500.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 14,
            },
            {
                "material_name": "Bulldozer D6 Size (Monthly Rental)",
                "material_category": "Heavy Equipment",
                "unit_price": Decimal("18500.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 14,
            },
            {
                "material_name": "Loader Wheel 950 Size 5-Yard Bucket",
                "material_category": "Heavy Equipment",
                "unit_price": Decimal("10500.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 10,
            },
            {
                "material_name": "Backhoe 420 Size (Monthly Rental)",
                "material_category": "Heavy Equipment",
                "unit_price": Decimal("4850.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 7,
            },
            {
                "material_name": "Compactor Vibratory Roller 10-Ton",
                "material_category": "Compaction Equipment",
                "unit_price": Decimal("3850.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 10,
            },
            {
                "material_name": "Generator 200kW Towable Diesel",
                "material_category": "Power Equipment",
                "unit_price": Decimal("2850.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 7,
            },
            {
                "material_name": "Light Tower LED 4x1000W Diesel",
                "material_category": "Site Lighting",
                "unit_price": Decimal("850.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 5,
            },
            {
                "material_name": "Forklift Rough Terrain 6000 lb Capacity",
                "material_category": "Material Handling",
                "unit_price": Decimal("4200.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 7,
            },
            {
                "material_name": "Scissor Lift 32 ft Electric",
                "material_category": "Aerial Equipment",
                "unit_price": Decimal("1850.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 5,
            },
            {
                "material_name": "Boom Lift Articulating 60 ft Diesel",
                "material_category": "Aerial Equipment",
                "unit_price": Decimal("3500.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 10,
            },
        ],
    },
    {
        "supplier_code": "SUP-GEO-14",
        "supplier_name": "GeoTech Site Materials",
        "supplier_category": "Site Work & Landscaping",
        "contact_person": "Laura Bennett",
        "email": "l.bennett@geotech.example",
        "phone": "+1-206-555-5200",
        "location": "Seattle, WA",
        "lead_time_days": 7,
        "reliability_score": Decimal("86.50"),
        "preferred_supplier": False,
        "status": "active",
        "materials": [
            {
                "material_name": "Topsoil Screened 18-inch Depth per CY",
                "material_category": "Landscaping",
                "unit_price": Decimal("45.00"),
                "currency_code": "USD",
                "moq": 50,
                "lead_time_days": 5,
            },
            {
                "material_name": "Gravel Base Course 3/4-inch Crushed",
                "material_category": "Base Material",
                "unit_price": Decimal("38.00"),
                "currency_code": "USD",
                "moq": 100,
                "lead_time_days": 3,
            },
            {
                "material_name": "Geotextile Fabric Non-Woven 8 oz",
                "material_category": "Site Fabric",
                "unit_price": Decimal("1.25"),
                "currency_code": "USD",
                "moq": 5000,
                "lead_time_days": 14,
            },
            {
                "material_name": "Erosion Control Blanket Straw/Coconut",
                "material_category": "Erosion Control",
                "unit_price": Decimal("2.85"),
                "currency_code": "USD",
                "moq": 2000,
                "lead_time_days": 10,
            },
            {
                "material_name": "Storm Drain Pipe HDPE 18-inch Diameter",
                "material_category": "Drainage",
                "unit_price": Decimal("48.00"),
                "currency_code": "USD",
                "moq": 200,
                "lead_time_days": 21,
            },
            {
                "material_name": "Catch Basin Precast 48-inch Diameter",
                "material_category": "Drainage Structures",
                "unit_price": Decimal("1850.00"),
                "currency_code": "USD",
                "moq": 5,
                "lead_time_days": 28,
            },
            {
                "material_name": "Asphalt Paving 2-inch Binder Course",
                "material_category": "Paving",
                "unit_price": Decimal("8.50"),
                "currency_code": "USD",
                "moq": 500,
                "lead_time_days": 7,
            },
            {
                "material_name": "Concrete Paving 6-inch 4000 PSI",
                "material_category": "Paving",
                "unit_price": Decimal("12.50"),
                "currency_code": "USD",
                "moq": 300,
                "lead_time_days": 10,
            },
            {
                "material_name": "Silt Fence 36-inch Height",
                "material_category": "Erosion Control",
                "unit_price": Decimal("3.50"),
                "currency_code": "USD",
                "moq": 1000,
                "lead_time_days": 7,
            },
            {
                "material_name": "Mulch Hardwood Shredded per CY",
                "material_category": "Landscaping",
                "unit_price": Decimal("35.00"),
                "currency_code": "USD",
                "moq": 50,
                "lead_time_days": 5,
            },
        ],
    },

    # ===== SPECIALTY & MISC SUPPLIERS (6) =====
    {
        "supplier_code": "SUP-OTI-15",
        "supplier_name": "Otis Elevator Company",
        "supplier_category": "Vertical Transportation",
        "contact_person": "Michelle Wong",
        "email": "m.wong@otis.example",
        "phone": "+1-860-555-6200",
        "location": "Farmington, CT",
        "lead_time_days": 210,
        "reliability_score": Decimal("95.00"),
        "preferred_supplier": True,
        "status": "active",
        "materials": [
            {
                "material_name": "Elevator Passenger Gearless 4000 lb 700 FPM",
                "material_category": "Elevators",
                "unit_price": Decimal("485000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 240,
            },
            {
                "material_name": "Elevator Freight 10,000 lb 200 FPM",
                "material_category": "Elevators",
                "unit_price": Decimal("285000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 220,
            },
            {
                "material_name": "Escalator 40-inch Width 100 FPM Indoor",
                "material_category": "Escalators",
                "unit_price": Decimal("385000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 210,
            },
            {
                "material_name": "Moving Walk 48-inch Width Horizontal",
                "material_category": "Moving Walks",
                "unit_price": Decimal("285000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 200,
            },
            {
                "material_name": "Elevator Modernization Package Existing 12-Stop",
                "material_category": "Modernization",
                "unit_price": Decimal("185000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 180,
            },
        ],
    },
    {
        "supplier_code": "SUP-KIM-16",
        "supplier_name": "Kimberly-Clark Safety Products",
        "supplier_category": "Safety & PPE",
        "contact_person": "Steven Harris",
        "email": "s.harris@kcsp.example",
        "phone": "+1-972-555-7300",
        "location": "Dallas, TX",
        "lead_time_days": 14,
        "reliability_score": Decimal("89.00"),
        "preferred_supplier": False,
        "status": "active",
        "materials": [
            {
                "material_name": "Hard Hat Class E ANSI Z89.1",
                "material_category": "Head Protection",
                "unit_price": Decimal("18.50"),
                "currency_code": "USD",
                "moq": 100,
                "lead_time_days": 10,
            },
            {
                "material_name": "Safety Glasses Anti-Fog Clear Lens",
                "material_category": "Eye Protection",
                "unit_price": Decimal("8.50"),
                "currency_code": "USD",
                "moq": 200,
                "lead_time_days": 7,
            },
            {
                "material_name": "Work Gloves Cut-Resistant Level 3",
                "material_category": "Hand Protection",
                "unit_price": Decimal("12.50"),
                "currency_code": "USD",
                "moq": 300,
                "lead_time_days": 10,
            },
            {
                "material_name": "Safety Vest High-Visibility Class 2",
                "material_category": "Body Protection",
                "unit_price": Decimal("8.85"),
                "currency_code": "USD",
                "moq": 200,
                "lead_time_days": 7,
            },
            {
                "material_name": "Steel Toe Boots Waterproof Size 10",
                "material_category": "Foot Protection",
                "unit_price": Decimal("125.00"),
                "currency_code": "USD",
                "moq": 50,
                "lead_time_days": 14,
            },
            {
                "material_name": "Respirator Half-Face N95 Disposable",
                "material_category": "Respiratory Protection",
                "unit_price": Decimal("3.50"),
                "currency_code": "USD",
                "moq": 1000,
                "lead_time_days": 7,
            },
            {
                "material_name": "Fall Arrest Harness Full-Body ANSI Z359",
                "material_category": "Fall Protection",
                "unit_price": Decimal("185.00"),
                "currency_code": "USD",
                "moq": 25,
                "lead_time_days": 14,
            },
            {
                "material_name": "First Aid Kit OSHA Compliant 150-Person",
                "material_category": "Emergency",
                "unit_price": Decimal("125.00"),
                "currency_code": "USD",
                "moq": 10,
                "lead_time_days": 7,
            },
        ],
    },
    {
        "supplier_code": "SUP-SIM-17",
        "supplier_name": "Simplex Fire Protection",
        "supplier_category": "Fire Safety Systems",
        "contact_person": "Rachel Green",
        "email": "r.green@simplex.example",
        "phone": "+1-617-555-8400",
        "location": "Boston, MA",
        "lead_time_days": 90,
        "reliability_score": Decimal("92.50"),
        "preferred_supplier": True,
        "status": "active",
        "materials": [
            {
                "material_name": "Fire Alarm Panel Addressable 500-Point",
                "material_category": "Fire Alarm",
                "unit_price": Decimal("28500.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 100,
            },
            {
                "material_name": "Smoke Detector Photoelectric Addressable",
                "material_category": "Fire Alarm Devices",
                "unit_price": Decimal("85.00"),
                "currency_code": "USD",
                "moq": 100,
                "lead_time_days": 45,
            },
            {
                "material_name": "Sprinkler Head Upright 155°F K=5.6",
                "material_category": "Fire Sprinklers",
                "unit_price": Decimal("4.85"),
                "currency_code": "USD",
                "moq": 1000,
                "lead_time_days": 30,
            },
            {
                "material_name": "Fire Extinguisher ABC 10 lb Wall Mount",
                "material_category": "Portable Fire Equipment",
                "unit_price": Decimal("85.00"),
                "currency_code": "USD",
                "moq": 50,
                "lead_time_days": 21,
            },
            {
                "material_name": "Fire Hose Cabinet 30-inch x 30-inch Recessed",
                "material_category": "Fire Hose Equipment",
                "unit_price": Decimal("485.00"),
                "currency_code": "USD",
                "moq": 20,
                "lead_time_days": 60,
            },
            {
                "material_name": "Emergency Light Battery Backup LED",
                "material_category": "Emergency Lighting",
                "unit_price": Decimal("125.00"),
                "currency_code": "USD",
                "moq": 50,
                "lead_time_days": 35,
            },
            {
                "material_name": "Exit Sign LED Green Running Man",
                "material_category": "Egress Marking",
                "unit_price": Decimal("65.00"),
                "currency_code": "USD",
                "moq": 100,
                "lead_time_days": 28,
            },
            {
                "material_name": "Fire Door Steel 90-Min 3x7 ft",
                "material_category": "Fire Doors",
                "unit_price": Decimal("1850.00"),
                "currency_code": "USD",
                "moq": 5,
                "lead_time_days": 75,
            },
        ],
    },
    {
        "supplier_code": "SUP-HON-18",
        "supplier_name": "Honeywell Building Automation",
        "supplier_category": "BMS & Controls",
        "contact_person": "Brian Thompson",
        "email": "b.thompson@honeywell.example",
        "phone": "+1-404-555-9500",
        "location": "Atlanta, GA",
        "lead_time_days": 110,
        "reliability_score": Decimal("91.50"),
        "preferred_supplier": True,
        "status": "active",
        "materials": [
            {
                "material_name": "Building Automation System Complete 500-Point",
                "material_category": "BMS",
                "unit_price": Decimal("185000.00"),
                "currency_code": "USD",
                "moq": 1,
                "lead_time_days": 140,
            },
            {
                "material_name": "DDC Controller Unitary 16-Point",
                "material_category": "Controls",
                "unit_price": Decimal("850.00"),
                "currency_code": "USD",
                "moq": 20,
                "lead_time_days": 60,
            },
            {
                "material_name": "Thermostat Smart Programmable",
                "material_category": "Controls",
                "unit_price": Decimal("185.00"),
                "currency_code": "USD",
                "moq": 50,
                "lead_time_days": 35,
            },
            {
                "material_name": "Valve Actuator Modulating 24V",
                "material_category": "Actuators",
                "unit_price": Decimal("285.00"),
                "currency_code": "USD",
                "moq": 40,
                "lead_time_days": 50,
            },
            {
                "material_name": "Damper Actuator Spring Return 24V",
                "material_category": "Actuators",
                "unit_price": Decimal("185.00"),
                "currency_code": "USD",
                "moq": 60,
                "lead_time_days": 45,
            },
            {
                "material_name": "Temperature Sensor Duct Mount RTD",
                "material_category": "Sensors",
                "unit_price": Decimal("125.00"),
                "currency_code": "USD",
                "moq": 100,
                "lead_time_days": 40,
            },
            {
                "material_name": "Pressure Transmitter 0-100 PSI",
                "material_category": "Sensors",
                "unit_price": Decimal("285.00"),
                "currency_code": "USD",
                "moq": 50,
                "lead_time_days": 45,
            },
            {
                "material_name": "Occupancy Sensor PIR Wall Mount",
                "material_category": "Sensors",
                "unit_price": Decimal("85.00"),
                "currency_code": "USD",
                "moq": 150,
                "lead_time_days": 30,
            },
        ],
    },
    {
        "supplier_code": "SUP-PEL-19",
        "supplier_name": "Pella Commercial Windows",
        "supplier_category": "Doors & Windows",
        "contact_person": "Jessica Martinez",
        "email": "j.martinez@pella.example",
        "phone": "+1-515-555-4200",
        "location": "Pella, IA",
        "lead_time_days": 95,
        "reliability_score": Decimal("87.00"),
        "preferred_supplier": False,
        "status": "active",
        "materials": [
            {
                "material_name": "Storefront Door Aluminum 3x7 ft Narrow Stile",
                "material_category": "Doors",
                "unit_price": Decimal("1850.00"),
                "currency_code": "USD",
                "moq": 10,
                "lead_time_days": 85,
            },
            {
                "material_name": "Commercial Window Fixed 4x6 ft Aluminum",
                "material_category": "Windows",
                "unit_price": Decimal("650.00"),
                "currency_code": "USD",
                "moq": 25,
                "lead_time_days": 90,
            },
            {
                "material_name": "Overhead Door Sectional Insulated 12x14 ft",
                "material_category": "Specialty Doors",
                "unit_price": Decimal("4850.00"),
                "currency_code": "USD",
                "moq": 2,
                "lead_time_days": 100,
            },
            {
                "material_name": "Hollow Metal Door 3x7 ft 18 Gauge",
                "material_category": "Doors",
                "unit_price": Decimal("485.00"),
                "currency_code": "USD",
                "moq": 20,
                "lead_time_days": 65,
            },
            {
                "material_name": "Door Frame Hollow Metal 16 Gauge",
                "material_category": "Frames",
                "unit_price": Decimal("285.00"),
                "currency_code": "USD",
                "moq": 30,
                "lead_time_days": 60,
            },
            {
                "material_name": "Door Hardware Lockset Commercial Grade",
                "material_category": "Hardware",
                "unit_price": Decimal("285.00"),
                "currency_code": "USD",
                "moq": 40,
                "lead_time_days": 45,
            },
            {
                "material_name": "Panic Exit Device Surface Mount",
                "material_category": "Hardware",
                "unit_price": Decimal("485.00"),
                "currency_code": "USD",
                "moq": 25,
                "lead_time_days": 50,
            },
            {
                "material_name": "Door Closer Hydraulic Heavy Duty",
                "material_category": "Hardware",
                "unit_price": Decimal("185.00"),
                "currency_code": "USD",
                "moq": 50,
                "lead_time_days": 40,
            },
        ],
    },
    {
        "supplier_code": "SUP-SHE-20",
        "supplier_name": "Sherwin-Williams Commercial Coatings",
        "supplier_category": "Paint & Coatings",
        "contact_person": "Nicole Adams",
        "email": "n.adams@sherwin.example",
        "phone": "+1-216-555-3700",
        "location": "Cleveland, OH",
        "lead_time_days": 14,
        "reliability_score": Decimal("90.00"),
        "preferred_supplier": True,
        "status": "active",
        "materials": [
            {
                "material_name": "Interior Paint Latex Eggshell 5-Gallon",
                "material_category": "Paint",
                "unit_price": Decimal("185.00"),
                "currency_code": "USD",
                "moq": 50,
                "lead_time_days": 10,
            },
            {
                "material_name": "Exterior Paint Acrylic Semi-Gloss 5-Gallon",
                "material_category": "Paint",
                "unit_price": Decimal("205.00"),
                "currency_code": "USD",
                "moq": 40,
                "lead_time_days": 14,
            },
            {
                "material_name": "Primer Interior/Exterior PVA 5-Gallon",
                "material_category": "Primer",
                "unit_price": Decimal("145.00"),
                "currency_code": "USD",
                "moq": 60,
                "lead_time_days": 7,
            },
            {
                "material_name": "Industrial Coating Epoxy Two-Part 5-Gallon",
                "material_category": "Industrial Coatings",
                "unit_price": Decimal("485.00"),
                "currency_code": "USD",
                "moq": 20,
                "lead_time_days": 21,
            },
            {
                "material_name": "Stain Wood Semi-Transparent Gallon",
                "material_category": "Stains",
                "unit_price": Decimal("65.00"),
                "currency_code": "USD",
                "moq": 100,
                "lead_time_days": 10,
            },
            {
                "material_name": "Caulk Paintable Latex 10 oz Tube",
                "material_category": "Sealants",
                "unit_price": Decimal("4.50"),
                "currency_code": "USD",
                "moq": 500,
                "lead_time_days": 7,
            },
            {
                "material_name": "Paint Roller Cover 9-inch 3/8 Nap",
                "material_category": "Application Tools",
                "unit_price": Decimal("3.85"),
                "currency_code": "USD",
                "moq": 200,
                "lead_time_days": 5,
            },
            {
                "material_name": "Drop Cloth Canvas 9x12 ft",
                "material_category": "Application Tools",
                "unit_price": Decimal("28.00"),
                "currency_code": "USD",
                "moq": 100,
                "lead_time_days": 7,
            },
        ],
    },
]


# ==============================================================================
# CREW MASTER DATA (50+ employees)
# ==============================================================================

CREW_MASTER_DATA: list[dict] = [
    # ===== PROJECT MANAGERS (5) =====
    {
        "employee_code": "CREW-PM-001",
        "employee_name": "Elena Vasquez",
        "skill_type": "Project Manager",
        "experience_years": 14,
        "daily_rate": Decimal("950.00"),
        "availability_status": "assigned",
        "certification": "PMP, OSHA 30, LEED AP",
        "location": "Seattle, WA",
        "phone": "+1-206-555-1001",
        "email": "elena.vasquez@constructaiq.example",
    },
    {
        "employee_code": "CREW-PM-002",
        "employee_name": "Nathan Holloway",
        "skill_type": "Project Manager",
        "experience_years": 10,
        "daily_rate": Decimal("880.00"),
        "availability_status": "available",
        "certification": "PMP, CCM, Six Sigma Green Belt",
        "location": "Denver, CO",
        "phone": "+1-720-555-1002",
        "email": "nathan.holloway@constructaiq.example",
    },
    {
        "employee_code": "CREW-PM-003",
        "employee_name": "Priya Sundaram",
        "skill_type": "Project Manager",
        "experience_years": 8,
        "daily_rate": Decimal("820.00"),
        "availability_status": "available",
        "certification": "PMP, LEED AP BD+C",
        "location": "Boston, MA",
        "phone": "+1-617-555-1003",
        "email": "priya.sundaram@constructaiq.example",
    },
    {
        "employee_code": "CREW-PM-004",
        "employee_name": "Marcus Chen",
        "skill_type": "Project Manager",
        "experience_years": 12,
        "daily_rate": Decimal("920.00"),
        "availability_status": "assigned",
        "certification": "PMP, CCM, OSHA 30",
        "location": "Austin, TX",
        "phone": "+1-512-555-1004",
        "email": "marcus.chen@constructaiq.example",
    },
    {
        "employee_code": "CREW-PM-005",
        "employee_name": "Sarah O'Connor",
        "skill_type": "Project Manager",
        "experience_years": 16,
        "daily_rate": Decimal("1020.00"),
        "availability_status": "available",
        "certification": "PMP, CCM, MBA Construction Management",
        "location": "Phoenix, AZ",
        "phone": "+1-602-555-1005",
        "email": "sarah.oconnor@constructaiq.example",
    },

    # ===== STRUCTURAL ENGINEERS (5) =====
    {
        "employee_code": "CREW-SE-001",
        "employee_name": "Robert Nakamura",
        "skill_type": "Structural Engineer",
        "experience_years": 11,
        "daily_rate": Decimal("820.00"),
        "availability_status": "assigned",
        "certification": "PE Structural, SE, LEED AP",
        "location": "Seattle, WA",
        "phone": "+1-206-555-2001",
        "email": "robert.nakamura@constructaiq.example",
    },
    {
        "employee_code": "CREW-SE-002",
        "employee_name": "Amara Okafor",
        "skill_type": "Structural Engineer",
        "experience_years": 8,
        "daily_rate": Decimal("760.00"),
        "availability_status": "available",
        "certification": "PE Structural, AISC",
        "location": "Boston, MA",
        "phone": "+1-617-555-2002",
        "email": "amara.okafor@constructaiq.example",
    },
    {
        "employee_code": "CREW-SE-003",
        "employee_name": "Carlos Mendes",
        "skill_type": "Structural Engineer",
        "experience_years": 16,
        "daily_rate": Decimal("980.00"),
        "availability_status": "assigned",
        "certification": "PE Structural, SE, AISC, ACI",
        "location": "San Francisco, CA",
        "phone": "+1-415-555-2003",
        "email": "carlos.mendes@constructaiq.example",
    },
    {
        "employee_code": "CREW-SE-004",
        "employee_name": "Diana Rodriguez",
        "skill_type": "Structural Engineer",
        "experience_years": 13,
        "daily_rate": Decimal("900.00"),
        "availability_status": "available",
        "certification": "PE Structural, SE",
        "location": "Denver, CO",
        "phone": "+1-720-555-2004",
        "email": "diana.rodriguez@constructaiq.example",
    },
    {
        "employee_code": "CREW-SE-005",
        "employee_name": "James Park",
        "skill_type": "Structural Engineer",
        "experience_years": 9,
        "daily_rate": Decimal("790.00"),
        "availability_status": "available",
        "certification": "PE Structural",
        "location": "Phoenix, AZ",
        "phone": "+1-602-555-2005",
        "email": "james.park@constructaiq.example",
    },

    # ===== MEP ENGINEERS (4) =====
    {
        "employee_code": "CREW-MEP-001",
        "employee_name": "Jennifer Liu",
        "skill_type": "MEP Engineer",
        "experience_years": 10,
        "daily_rate": Decimal("850.00"),
        "availability_status": "assigned",
        "certification": "PE Mechanical, LEED AP, CEM",
        "location": "Boston, MA",
        "phone": "+1-617-555-3001",
        "email": "jennifer.liu@constructaiq.example",
    },
    {
        "employee_code": "CREW-MEP-002",
        "employee_name": "David Kim",
        "skill_type": "MEP Engineer",
        "experience_years": 12,
        "daily_rate": Decimal("920.00"),
        "availability_status": "available",
        "certification": "PE Electrical, LEED AP",
        "location": "Austin, TX",
        "phone": "+1-512-555-3002",
        "email": "david.kim@constructaiq.example",
    },
    {
        "employee_code": "CREW-MEP-003",
        "employee_name": "Angela Foster",
        "skill_type": "MEP Engineer",
        "experience_years": 8,
        "daily_rate": Decimal("780.00"),
        "availability_status": "available",
        "certification": "PE Plumbing, LEED AP",
        "location": "Phoenix, AZ",
        "phone": "+1-602-555-3003",
        "email": "angela.foster@constructaiq.example",
    },
    {
        "employee_code": "CREW-MEP-004",
        "employee_name": "Michael Torres",
        "skill_type": "MEP Engineer",
        "experience_years": 14,
        "daily_rate": Decimal("970.00"),
        "availability_status": "assigned",
        "certification": "PE Mechanical, CEM, BEMP",
        "location": "Denver, CO",
        "phone": "+1-720-555-3004",
        "email": "michael.torres@constructaiq.example",
    },

    # ===== ARCHITECTS (3) =====
    {
        "employee_code": "CREW-ARC-001",
        "employee_name": "Isabella Martinez",
        "skill_type": "Architect",
        "experience_years": 12,
        "daily_rate": Decimal("900.00"),
        "availability_status": "available",
        "certification": "AIA, LEED AP BD+C, NCARB",
        "location": "Seattle, WA",
        "phone": "+1-206-555-4001",
        "email": "isabella.martinez@constructaiq.example",
    },
    {
        "employee_code": "CREW-ARC-002",
        "employee_name": "Thomas Wright",
        "skill_type": "Architect",
        "experience_years": 15,
        "daily_rate": Decimal("1050.00"),
        "availability_status": "assigned",
        "certification": "AIA, LEED Fellow, NCARB",
        "location": "Boston, MA",
        "phone": "+1-617-555-4002",
        "email": "thomas.wright@constructaiq.example",
    },
    {
        "employee_code": "CREW-ARC-003",
        "employee_name": "Rachel Green",
        "skill_type": "Architect",
        "experience_years": 9,
        "daily_rate": Decimal("820.00"),
        "availability_status": "available",
        "certification": "AIA, LEED AP",
        "location": "Austin, TX",
        "phone": "+1-512-555-4003",
        "email": "rachel.green@constructaiq.example",
    },

    # ===== GENERAL CONTRACTORS (4) =====
    {
        "employee_code": "CREW-GC-001",
        "employee_name": "Tom Bradley",
        "skill_type": "General Contractor",
        "experience_years": 18,
        "daily_rate": Decimal("780.00"),
        "availability_status": "assigned",
        "certification": "OSHA 30, First Aid, CGC",
        "location": "Denver, CO",
        "phone": "+1-720-555-5001",
        "email": "tom.bradley@constructaiq.example",
    },
    {
        "employee_code": "CREW-GC-002",
        "employee_name": "Maria Gonzalez",
        "skill_type": "General Contractor",
        "experience_years": 15,
        "daily_rate": Decimal("750.00"),
        "availability_status": "available",
        "certification": "OSHA 30, CGC, MBA",
        "location": "Phoenix, AZ",
        "phone": "+1-602-555-5002",
        "email": "maria.gonzalez@constructaiq.example",
    },
    {
        "employee_code": "CREW-GC-003",
        "employee_name": "Frank Morrison",
        "skill_type": "General Contractor",
        "experience_years": 20,
        "daily_rate": Decimal("820.00"),
        "availability_status": "assigned",
        "certification": "OSHA 30, CGC, CCM",
        "location": "Austin, TX",
        "phone": "+1-512-555-5003",
        "email": "frank.morrison@constructaiq.example",
    },
    {
        "employee_code": "CREW-GC-004",
        "employee_name": "Laura Bennett",
        "skill_type": "General Contractor",
        "experience_years": 12,
        "daily_rate": Decimal("720.00"),
        "availability_status": "available",
        "certification": "OSHA 30, CGC",
        "location": "Seattle, WA",
        "phone": "+1-206-555-5004",
        "email": "laura.bennett@constructaiq.example",
    },

    # ===== SUPERINTENDENTS (4) =====
    {
        "employee_code": "CREW-SUP-001",
        "employee_name": "Kevin Johnson",
        "skill_type": "Superintendent",
        "experience_years": 16,
        "daily_rate": Decimal("720.00"),
        "availability_status": "assigned",
        "certification": "OSHA 30, First Aid, CPR",
        "location": "Seattle, WA",
        "phone": "+1-206-555-6001",
        "email": "kevin.johnson@constructaiq.example",
    },
    {
        "employee_code": "CREW-SUP-002",
        "employee_name": "Patricia Miller",
        "skill_type": "Superintendent",
        "experience_years": 13,
        "daily_rate": Decimal("690.00"),
        "availability_status": "available",
        "certification": "OSHA 30, First Aid",
        "location": "Denver, CO",
        "phone": "+1-720-555-6002",
        "email": "patricia.miller@constructaiq.example",
    },
    {
        "employee_code": "CREW-SUP-003",
        "employee_name": "Daniel Wilson",
        "skill_type": "Superintendent",
        "experience_years": 19,
        "daily_rate": Decimal("760.00"),
        "availability_status": "assigned",
        "certification": "OSHA 30, CSP, First Aid",
        "location": "Boston, MA",
        "phone": "+1-617-555-6003",
        "email": "daniel.wilson@constructaiq.example",
    },
    {
        "employee_code": "CREW-SUP-004",
        "employee_name": "Michelle Davis",
        "skill_type": "Superintendent",
        "experience_years": 11,
        "daily_rate": Decimal("680.00"),
        "availability_status": "available",
        "certification": "OSHA 30, First Aid",
        "location": "Phoenix, AZ",
        "phone": "+1-602-555-6004",
        "email": "michelle.davis@constructaiq.example",
    },

    # ===== FOREMEN (6) =====
    {
        "employee_code": "CREW-FOR-001",
        "employee_name": "John Anderson",
        "skill_type": "Foreman - Concrete",
        "experience_years": 14,
        "daily_rate": Decimal("650.00"),
        "availability_status": "assigned",
        "certification": "OSHA 30, ACI Certification",
        "location": "Denver, CO",
        "phone": "+1-720-555-7001",
        "email": "john.anderson@constructaiq.example",
    },
    {
        "employee_code": "CREW-FOR-002",
        "employee_name": "Steven Harris",
        "skill_type": "Foreman - Steel",
        "experience_years": 12,
        "daily_rate": Decimal("640.00"),
        "availability_status": "available",
        "certification": "OSHA 30, AWS D1.1",
        "location": "Seattle, WA",
        "phone": "+1-206-555-7002",
        "email": "steven.harris@constructaiq.example",
    },
    {
        "employee_code": "CREW-FOR-003",
        "employee_name": "Nicole Adams",
        "skill_type": "Foreman - Electrical",
        "experience_years": 10,
        "daily_rate": Decimal("630.00"),
        "availability_status": "available",
        "certification": "OSHA 30, Journeyman Electrician",
        "location": "Austin, TX",
        "phone": "+1-512-555-7003",
        "email": "nicole.adams@constructaiq.example",
    },
    {
        "employee_code": "CREW-FOR-004",
        "employee_name": "Brian Thompson",
        "skill_type": "Foreman - HVAC",
        "experience_years": 13,
        "daily_rate": Decimal("645.00"),
        "availability_status": "assigned",
        "certification": "OSHA 30, EPA 608, NATE",
        "location": "Phoenix, AZ",
        "phone": "+1-602-555-7004",
        "email": "brian.thompson@constructaiq.example",
    },
    {
        "employee_code": "CREW-FOR-005",
        "employee_name": "Jessica White",
        "skill_type": "Foreman - Plumbing",
        "experience_years": 11,
        "daily_rate": Decimal("635.00"),
        "availability_status": "available",
        "certification": "OSHA 30, Master Plumber",
        "location": "Boston, MA",
        "phone": "+1-617-555-7005",
        "email": "jessica.white@constructaiq.example",
    },
    {
        "employee_code": "CREW-FOR-006",
        "employee_name": "Ryan Martinez",
        "skill_type": "Foreman - Carpentry",
        "experience_years": 15,
        "daily_rate": Decimal("655.00"),
        "availability_status": "assigned",
        "certification": "OSHA 30, Master Carpenter",
        "location": "Denver, CO",
        "phone": "+1-720-555-7006",
        "email": "ryan.martinez@constructaiq.example",
    },

    # ===== SAFETY OFFICERS (3) =====
    {
        "employee_code": "CREW-SAF-001",
        "employee_name": "Christopher Lee",
        "skill_type": "Safety Officer",
        "experience_years": 9,
        "daily_rate": Decimal("700.00"),
        "availability_status": "assigned",
        "certification": "CSP, OSHA 30, CHST",
        "location": "Seattle, WA",
        "phone": "+1-206-555-8001",
        "email": "christopher.lee@constructaiq.example",
    },
    {
        "employee_code": "CREW-SAF-002",
        "employee_name": "Amanda Taylor",
        "skill_type": "Safety Officer",
        "experience_years": 7,
        "daily_rate": Decimal("680.00"),
        "availability_status": "available",
        "certification": "CSP, OSHA 30",
        "location": "Boston, MA",
        "phone": "+1-617-555-8002",
        "email": "amanda.taylor@constructaiq.example",
    },
    {
        "employee_code": "CREW-SAF-003",
        "employee_name": "Robert Garcia",
        "skill_type": "Safety Officer",
        "experience_years": 11,
        "daily_rate": Decimal("720.00"),
        "availability_status": "assigned",
        "certification": "CSP, OSHA 30, CHST, CIH",
        "location": "Austin, TX",
        "phone": "+1-512-555-8003",
        "email": "robert.garcia@constructaiq.example",
    },

    # ===== QUALITY INSPECTORS (4) =====
    {
        "employee_code": "CREW-QC-001",
        "employee_name": "Karen White",
        "skill_type": "Quality Inspector",
        "experience_years": 10,
        "daily_rate": Decimal("670.00"),
        "availability_status": "available",
        "certification": "ACI, OSHA 30, CWI",
        "location": "Denver, CO",
        "phone": "+1-720-555-9001",
        "email": "karen.white@constructaiq.example",
    },
    {
        "employee_code": "CREW-QC-002",
        "employee_name": "George Robinson",
        "skill_type": "Quality Inspector",
        "experience_years": 12,
        "daily_rate": Decimal("690.00"),
        "availability_status": "assigned",
        "certification": "ACI, AWS CWI, OSHA 30",
        "location": "Seattle, WA",
        "phone": "+1-206-555-9002",
        "email": "george.robinson@constructaiq.example",
    },
    {
        "employee_code": "CREW-QC-003",
        "employee_name": "Lisa Brown",
        "skill_type": "Quality Inspector",
        "experience_years": 8,
        "daily_rate": Decimal("660.00"),
        "availability_status": "available",
        "certification": "ACI, OSHA 30",
        "location": "Phoenix, AZ",
        "phone": "+1-602-555-9003",
        "email": "lisa.brown@constructaiq.example",
    },
    {
        "employee_code": "CREW-QC-004",
        "employee_name": "William Clark",
        "skill_type": "Quality Inspector",
        "experience_years": 14,
        "daily_rate": Decimal("710.00"),
        "availability_status": "assigned",
        "certification": "ACI, AWS CWI, ASNT Level II",
        "location": "Boston, MA",
        "phone": "+1-617-555-9004",
        "email": "william.clark@constructaiq.example",
    },

    # ===== ESTIMATORS (3) =====
    {
        "employee_code": "CREW-EST-001",
        "employee_name": "Eric Johnson",
        "skill_type": "Estimator",
        "experience_years": 11,
        "daily_rate": Decimal("850.00"),
        "availability_status": "available",
        "certification": "CPE, OSHA 30",
        "location": "Austin, TX",
        "phone": "+1-512-555-1101",
        "email": "eric.johnson@constructaiq.example",
    },
    {
        "employee_code": "CREW-EST-002",
        "employee_name": "Samantha Rodriguez",
        "skill_type": "Estimator",
        "experience_years": 9,
        "daily_rate": Decimal("820.00"),
        "availability_status": "available",
        "certification": "CPE",
        "location": "Denver, CO",
        "phone": "+1-720-555-1102",
        "email": "samantha.rodriguez@constructaiq.example",
    },
    {
        "employee_code": "CREW-EST-003",
        "employee_name": "Timothy Moore",
        "skill_type": "Estimator",
        "experience_years": 13,
        "daily_rate": Decimal("890.00"),
        "availability_status": "assigned",
        "certification": "CPE, CCM",
        "location": "Phoenix, AZ",
        "phone": "+1-602-555-1103",
        "email": "timothy.moore@constructaiq.example",
    },

    # ===== SPECIALIZED TRADES (9+) =====
    {
        "employee_code": "CREW-WEL-001",
        "employee_name": "Mark Jackson",
        "skill_type": "Welder - Certified",
        "experience_years": 12,
        "daily_rate": Decimal("620.00"),
        "availability_status": "available",
        "certification": "AWS CWB, OSHA 10",
        "location": "Seattle, WA",
        "phone": "+1-206-555-1201",
        "email": "mark.jackson@constructaiq.example",
    },
    {
        "employee_code": "CREW-ELE-001",
        "employee_name": "Paul Martinez",
        "skill_type": "Electrician - Journeyman",
        "experience_years": 10,
        "daily_rate": Decimal("600.00"),
        "availability_status": "assigned",
        "certification": "Journeyman License, OSHA 10",
        "location": "Denver, CO",
        "phone": "+1-720-555-1202",
        "email": "paul.martinez@constructaiq.example",
    },
    {
        "employee_code": "CREW-PLU-001",
        "employee_name": "Andrew Lewis",
        "skill_type": "Plumber - Journeyman",
        "experience_years": 11,
        "daily_rate": Decimal("610.00"),
        "availability_status": "available",
        "certification": "Journeyman Plumber, OSHA 10",
        "location": "Boston, MA",
        "phone": "+1-617-555-1203",
        "email": "andrew.lewis@constructaiq.example",
    },
    {
        "employee_code": "CREW-HVA-001",
        "employee_name": "Matthew Walker",
        "skill_type": "HVAC Technician",
        "experience_years": 9,
        "daily_rate": Decimal("590.00"),
        "availability_status": "assigned",
        "certification": "EPA 608, NATE, OSHA 10",
        "location": "Phoenix, AZ",
        "phone": "+1-602-555-1204",
        "email": "matthew.walker@constructaiq.example",
    },
    {
        "employee_code": "CREW-CAR-001",
        "employee_name": "Joseph Young",
        "skill_type": "Carpenter - Finish",
        "experience_years": 13,
        "daily_rate": Decimal("615.00"),
        "availability_status": "available",
        "certification": "OSHA 10, Journeyman",
        "location": "Austin, TX",
        "phone": "+1-512-555-1205",
        "email": "joseph.young@constructaiq.example",
    },
    {
        "employee_code": "CREW-MAS-001",
        "employee_name": "Richard Allen",
        "skill_type": "Mason - Brick/Stone",
        "experience_years": 14,
        "daily_rate": Decimal("625.00"),
        "availability_status": "available",
        "certification": "OSHA 10, MCAA",
        "location": "Boston, MA",
        "phone": "+1-617-555-1206",
        "email": "richard.allen@constructaiq.example",
    },
    {
        "employee_code": "CREW-CRA-001",
        "employee_name": "Charles King",
        "skill_type": "Crane Operator",
        "experience_years": 16,
        "daily_rate": Decimal("720.00"),
        "availability_status": "assigned",
        "certification": "NCCCO Tower Crane, OSHA 10",
        "location": "Seattle, WA",
        "phone": "+1-206-555-1207",
        "email": "charles.king@constructaiq.example",
    },
    {
        "employee_code": "CREW-PAI-001",
        "employee_name": "Donald Scott",
        "skill_type": "Painter - Commercial",
        "experience_years": 10,
        "daily_rate": Decimal("580.00"),
        "availability_status": "available",
        "certification": "OSHA 10, PDCA",
        "location": "Denver, CO",
        "phone": "+1-720-555-1208",
        "email": "donald.scott@constructaiq.example",
    },
    {
        "employee_code": "CREW-ROO-001",
        "employee_name": "Kenneth Adams",
        "skill_type": "Roofer - Commercial",
        "experience_years": 11,
        "daily_rate": Decimal("600.00"),
        "availability_status": "assigned",
        "certification": "OSHA 10, Fall Protection",
        "location": "Phoenix, AZ",
        "phone": "+1-602-555-1209",
        "email": "kenneth.adams@constructaiq.example",
    },
    {
        "employee_code": "CREW-GLA-001",
        "employee_name": "Edward Baker",
        "skill_type": "Glazier - Curtain Wall",
        "experience_years": 12,
        "daily_rate": Decimal("640.00"),
        "availability_status": "available",
        "certification": "OSHA 10, IGMA",
        "location": "Austin, TX",
        "phone": "+1-512-555-1210",
        "email": "edward.baker@constructaiq.example",
    },
]
